import Setlec.Kernel.Basis.Names

/-!
# Recognized standard axioms and their prerequisite shapes

The lean-inductive-models preprocessor's generated routes may use the
standard axioms `propext` and `Classical.choice`.  Both are true in
the set-theoretic model — `propext` by extensionality of propositions
(derived through the stored `Iff` recursor), `Classical.choice` by
global choice (through the stored `Nonempty` recursor) — so the
checker accepts exactly these two axioms, after pinning their types
and the *shapes of the inductives they quantify over* to what the
preprocessor emits.  Raw pins below; the annotated forms (what the
checker's own annotation produces for them, in dependency order) are
generated by `AnnotateBasis.lean` — do not edit them by hand.
-/

namespace Setlec

open Name (anonymous)

/-- The name `propext`. -/
def propextName : Name := anonymous |>.str "propext"

/-- The name `Classical.choice`. -/
def choiceName : Name := (anonymous |>.str "Classical") |>.str "choice"

/-- The name `Iff`. -/
def iffName : Name := anonymous |>.str "Iff"

/-- The name `Iff.intro`. -/
def iffIntroName : Name := iffName |>.str "intro"

/-- The name `Iff.rec`. -/
def iffRecName : Name := iffName |>.str "rec"

/-- The name `Nonempty`. -/
def nonemptyName : Name := anonymous |>.str "Nonempty"

/-- The name `Nonempty.intro`. -/
def nonemptyIntroName : Name := nonemptyName |>.str "intro"

/-- The name `Nonempty.rec`. -/
def nonemptyRecName : Name := nonemptyName |>.str "rec"

/-- Erase binder and `fvar` names (annotations preserved): the
standard shapes are pinned up to the exporter's unstable hygienic
binder names, which the interpretation never reads. -/
def Expr.eraseNames : Expr → Expr
  | .bvar i => .bvar i
  | .fvar i _ ty => .fvar i .anonymous ty.eraseNames
  | .sort u => .sort u
  | .const n us => .const n us
  | .app f a => .app f.eraseNames a.eraseNames
  | .lam _ ty b m => .lam .anonymous ty.eraseNames b.eraseNames m
  | .forallE _ ty b m => .forallE .anonymous ty.eraseNames b.eraseNames m
  | .letE _ ty v b => .letE .anonymous ty.eraseNames v.eraseNames
      b.eraseNames
  | .lit l => .lit l
  | .proj s i e => .proj s i e.eraseNames

/-- Shape comparison for the standard pins: exact name, level
parameters and counts, type up to binder names. -/
def ConstantVal.matchesPin (cv pin : ConstantVal) : Bool :=
  cv.name = pin.name && cv.levelParams = pin.levelParams &&
    cv.type.eraseNames == pin.type.eraseNames

/-- The raw `Iff` family and `propext`, as the preprocessor emits
them (dependency order). -/
def iffFamily : List ConstantInfo := [
  .indInfo ⟨(anonymous |>.str "Iff"), [], (.forallE (anonymous |>.str "a") (.sort (.zero)) (.forallE (anonymous |>.str "b") (.sort (.zero)) (.sort (.zero)) ⟨.default, none⟩) ⟨.default, none⟩)⟩ {},
  .ctorInfo ⟨((anonymous |>.str "Iff") |>.str "intro"), [], (.forallE (anonymous |>.str "a") (.sort (.zero)) (.forallE (anonymous |>.str "b") (.sort (.zero)) (.forallE (anonymous |>.str "mp") (.forallE (anonymous) (.bvar 1) (.bvar 1) ⟨.default, none⟩) (.forallE (anonymous |>.str "mpr") (.forallE (anonymous) (.bvar 1) (.bvar 3) ⟨.default, none⟩) (.app (.app (.const (anonymous |>.str "Iff") []) (.bvar 3)) (.bvar 2)) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.implicit, none⟩) ⟨.implicit, none⟩)⟩ 2 2,
  .recInfo ⟨((anonymous |>.str "Iff") |>.str "rec"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "a") (.sort (.zero)) (.forallE (anonymous |>.str "b") (.sort (.zero)) (.forallE (anonymous |>.str "motive") (.forallE (anonymous |>.str "t") (.app (.app (.const (anonymous |>.str "Iff") []) (.bvar 1)) (.bvar 0)) (.sort (.param (anonymous |>.str "u"))) ⟨.default, none⟩) (.forallE (anonymous |>.str "intro") (.forallE (anonymous |>.str "mp") (.forallE (anonymous |>.str "right") (.bvar 2) (.bvar 2) ⟨.default, none⟩) (.forallE (anonymous |>.str "mpr") (.forallE (anonymous) (.bvar 2) (.bvar 4) ⟨.default, none⟩) (.app (.bvar 2) (.app (.app (.app (.app (.const ((anonymous |>.str "Iff") |>.str "intro") []) (.bvar 4)) (.bvar 3)) (.bvar 1)) (.bvar 0))) ⟨.default, none⟩) ⟨.default, none⟩) (.forallE (anonymous |>.str "t") (.app (.app (.const (anonymous |>.str "Iff") []) (.bvar 3)) (.bvar 2)) (.app (.bvar 2) (.bvar 0)) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.implicit, none⟩) ⟨.implicit, none⟩) ⟨.implicit, none⟩)⟩ 2 1 1 0 []]

/-- The raw `propext` declaration. -/
def propextRaw : ConstantVal := ⟨(anonymous |>.str "propext"), [], (.forallE (anonymous |>.str "a") (.sort (.zero)) (.forallE (anonymous |>.str "b") (.sort (.zero)) (.forallE (anonymous) (.app (.app (.const (anonymous |>.str "Iff") []) (.bvar 1)) (.bvar 0)) (.app (.app (.app (.const (anonymous |>.str "Eq") [(.succ (.zero))]) (.sort (.zero))) (.bvar 2)) (.bvar 1)) ⟨.default, none⟩) ⟨.implicit, none⟩) ⟨.implicit, none⟩)⟩

/-- The raw `Nonempty` family. -/
def nonemptyFamily : List ConstantInfo := [
  .indInfo ⟨(anonymous |>.str "Nonempty"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.sort (.zero)) ⟨.default, none⟩)⟩ {},
  .ctorInfo ⟨((anonymous |>.str "Nonempty") |>.str "intro"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous |>.str "val") (.bvar 0) (.app (.const (anonymous |>.str "Nonempty") [(.param (anonymous |>.str "u"))]) (.bvar 1)) ⟨.default, none⟩) ⟨.implicit, none⟩)⟩ 1 1,
  .recInfo ⟨((anonymous |>.str "Nonempty") |>.str "rec"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous |>.str "motive") (.forallE (anonymous |>.str "t") (.app (.const (anonymous |>.str "Nonempty") [(.param (anonymous |>.str "u"))]) (.bvar 0)) (.sort (.zero)) ⟨.default, none⟩) (.forallE (anonymous |>.str "intro") (.forallE (anonymous |>.str "val") (.bvar 1) (.app (.bvar 1) (.app (.app (.const ((anonymous |>.str "Nonempty") |>.str "intro") [(.param (anonymous |>.str "u"))]) (.bvar 2)) (.bvar 0))) ⟨.default, none⟩) (.forallE (anonymous |>.str "t") (.app (.const (anonymous |>.str "Nonempty") [(.param (anonymous |>.str "u"))]) (.bvar 2)) (.app (.bvar 2) (.bvar 0)) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.implicit, none⟩) ⟨.implicit, none⟩)⟩ 1 1 1 0 []]

/-- The raw `Classical.choice` declaration. -/
def choiceRaw : ConstantVal := ⟨((anonymous |>.str "Classical") |>.str "choice"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous) (.app (.const (anonymous |>.str "Nonempty") [(.param (anonymous |>.str "u"))]) (.bvar 0)) (.bvar 1) ⟨.default, none⟩) ⟨.implicit, none⟩)⟩

/-- Annotated standard-shape pin (generated). -/
def iffA : ConstantInfo :=
  Setlec.ConstantInfo.indInfo
  { name := Setlec.Name.str (Setlec.Name.anonymous) "Iff",
    levelParams := [],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "a")
              (Setlec.Expr.sort (Setlec.Level.zero))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "b")
                (Setlec.Expr.sort (Setlec.Level.zero))
                (Setlec.Expr.sort (Setlec.Level.zero))
                { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.succ (Setlec.Level.zero)) })
              { bi := Setlec.BinderInfo.default,
                cod := some (Setlec.Level.imax
                         (Setlec.Level.succ (Setlec.Level.zero))
                         (Setlec.Level.succ (Setlec.Level.zero))) } }
  { eta := false,
    etaCtor := Setlec.Name.anonymous,
    etaParams := 0,
    etaFields := 0,
    unitlike := false,
    unitParams := 0,
    ruleK := false }

/-- Annotated standard-shape pin (generated). -/
def iffIntroA : ConstantInfo :=
  Setlec.ConstantInfo.ctorInfo
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Iff") "intro",
    levelParams := [],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "a")
              (Setlec.Expr.sort (Setlec.Level.zero))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "b")
                (Setlec.Expr.sort (Setlec.Level.zero))
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "mp")
                  (Setlec.Expr.forallE
                    (Setlec.Name.anonymous)
                    (Setlec.Expr.bvar 1)
                    (Setlec.Expr.bvar 1)
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "mpr")
                    (Setlec.Expr.forallE
                      (Setlec.Name.anonymous)
                      (Setlec.Expr.bvar 1)
                      (Setlec.Expr.bvar 3)
                      { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Iff") [])
                        (Setlec.Expr.bvar 3))
                      (Setlec.Expr.bvar 2))
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))
                             (Setlec.Level.zero)) })
                { bi := Setlec.BinderInfo.implicit,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))
                           (Setlec.Level.imax
                             (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))
                             (Setlec.Level.zero))) })
              { bi := Setlec.BinderInfo.implicit,
                cod := some (Setlec.Level.imax
                         (Setlec.Level.succ (Setlec.Level.zero))
                         (Setlec.Level.imax
                           (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))
                           (Setlec.Level.imax
                             (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))
                             (Setlec.Level.zero)))) } }
  2
  2

/-- Annotated standard-shape pin (generated). -/
def iffRecA : ConstantInfo :=
  Setlec.ConstantInfo.recInfo
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Iff") "rec",
    levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "a")
              (Setlec.Expr.sort (Setlec.Level.zero))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "b")
                (Setlec.Expr.sort (Setlec.Level.zero))
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "motive")
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "t")
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Iff") [])
                        (Setlec.Expr.bvar 1))
                      (Setlec.Expr.bvar 0))
                    (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
                    { bi := Setlec.BinderInfo.default,
                      cod := some (Setlec.Level.succ
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))) })
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "intro")
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "mp")
                      (Setlec.Expr.forallE
                        (Setlec.Name.str (Setlec.Name.anonymous) "right")
                        (Setlec.Expr.bvar 2)
                        (Setlec.Expr.bvar 2)
                        { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                      (Setlec.Expr.forallE
                        (Setlec.Name.str (Setlec.Name.anonymous) "mpr")
                        (Setlec.Expr.forallE
                          (Setlec.Name.anonymous)
                          (Setlec.Expr.bvar 2)
                          (Setlec.Expr.bvar 4)
                          { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                        (Setlec.Expr.app
                          (Setlec.Expr.bvar 2)
                          (Setlec.Expr.app
                            (Setlec.Expr.app
                              (Setlec.Expr.app
                                (Setlec.Expr.app
                                  (Setlec.Expr.const
                                    (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Iff") "intro")
                                    [])
                                  (Setlec.Expr.bvar 4))
                                (Setlec.Expr.bvar 3))
                              (Setlec.Expr.bvar 1))
                            (Setlec.Expr.bvar 0)))
                        { bi := Setlec.BinderInfo.default,
                          cod := some (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")) })
                      { bi := Setlec.BinderInfo.default,
                        cod := some (Setlec.Level.imax
                                 (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))) })
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "t")
                      (Setlec.Expr.app
                        (Setlec.Expr.app
                          (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Iff") [])
                          (Setlec.Expr.bvar 3))
                        (Setlec.Expr.bvar 2))
                      (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 0))
                      { bi := Setlec.BinderInfo.default,
                        cod := some (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")) })
                    { bi := Setlec.BinderInfo.default,
                      cod := some (Setlec.Level.imax
                               (Setlec.Level.zero)
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))) })
                  { bi := Setlec.BinderInfo.implicit,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))
                               (Setlec.Level.imax
                                 (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))))
                             (Setlec.Level.imax
                               (Setlec.Level.zero)
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))) })
                { bi := Setlec.BinderInfo.implicit,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.imax
                             (Setlec.Level.zero)
                             (Setlec.Level.succ (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))))
                           (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))
                               (Setlec.Level.imax
                                 (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))))
                             (Setlec.Level.imax
                               (Setlec.Level.zero)
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))))) })
              { bi := Setlec.BinderInfo.implicit,
                cod := some (Setlec.Level.imax
                         (Setlec.Level.succ (Setlec.Level.zero))
                         (Setlec.Level.imax
                           (Setlec.Level.imax
                             (Setlec.Level.zero)
                             (Setlec.Level.succ (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))))
                           (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))
                               (Setlec.Level.imax
                                 (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))))
                             (Setlec.Level.imax
                               (Setlec.Level.zero)
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))))) } }
  2
  1
  1
  0
  []

/-- Annotated standard-shape pin (generated). -/
def nonemptyA : ConstantInfo :=
  Setlec.ConstantInfo.indInfo
  { name := Setlec.Name.str (Setlec.Name.anonymous) "Nonempty",
    levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "α")
              (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
              (Setlec.Expr.sort (Setlec.Level.zero))
              { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.succ (Setlec.Level.zero)) } }
  { eta := false,
    etaCtor := Setlec.Name.anonymous,
    etaParams := 0,
    etaFields := 0,
    unitlike := false,
    unitParams := 0,
    ruleK := false }

/-- Annotated standard-shape pin (generated). -/
def nonemptyIntroA : ConstantInfo :=
  Setlec.ConstantInfo.ctorInfo
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty") "intro",
    levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "α")
              (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "val")
                (Setlec.Expr.bvar 0)
                (Setlec.Expr.app
                  (Setlec.Expr.const
                    (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty")
                    [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                  (Setlec.Expr.bvar 1))
                { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
              { bi := Setlec.BinderInfo.implicit,
                cod := some (Setlec.Level.imax
                         (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                         (Setlec.Level.zero)) } }
  1
  1

/-- Annotated standard-shape pin (generated). -/
def nonemptyRecA : ConstantInfo :=
  Setlec.ConstantInfo.recInfo
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty") "rec",
    levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "α")
              (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "motive")
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "t")
                  (Setlec.Expr.app
                    (Setlec.Expr.const
                      (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty")
                      [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                    (Setlec.Expr.bvar 0))
                  (Setlec.Expr.sort (Setlec.Level.zero))
                  { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.succ (Setlec.Level.zero)) })
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "intro")
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "val")
                    (Setlec.Expr.bvar 1)
                    (Setlec.Expr.app
                      (Setlec.Expr.bvar 1)
                      (Setlec.Expr.app
                        (Setlec.Expr.app
                          (Setlec.Expr.const
                            (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty") "intro")
                            [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                          (Setlec.Expr.bvar 2))
                        (Setlec.Expr.bvar 0)))
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "t")
                    (Setlec.Expr.app
                      (Setlec.Expr.const
                        (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty")
                        [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                      (Setlec.Expr.bvar 2))
                    (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 0))
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero)) })
                { bi := Setlec.BinderInfo.implicit,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.zero))
                           (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))) })
              { bi := Setlec.BinderInfo.implicit,
                cod := some (Setlec.Level.imax
                         (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.succ (Setlec.Level.zero)))
                         (Setlec.Level.imax
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.zero))
                           (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero)))) } }
  1
  1
  1
  0
  []

/-- Annotated standard-shape pin (generated). -/
def propextA : ConstantVal :=
  { name := Setlec.Name.str (Setlec.Name.anonymous) "propext",
      levelParams := [],
      type := Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "a")
                (Setlec.Expr.sort (Setlec.Level.zero))
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "b")
                  (Setlec.Expr.sort (Setlec.Level.zero))
                  (Setlec.Expr.forallE
                    (Setlec.Name.anonymous)
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Iff") [])
                        (Setlec.Expr.bvar 1))
                      (Setlec.Expr.bvar 0))
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.app
                          (Setlec.Expr.const
                            (Setlec.Name.str (Setlec.Name.anonymous) "Eq")
                            [Setlec.Level.succ (Setlec.Level.zero)])
                          (Setlec.Expr.sort (Setlec.Level.zero)))
                        (Setlec.Expr.bvar 2))
                      (Setlec.Expr.bvar 1))
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                  { bi := Setlec.BinderInfo.implicit,
                    cod := some (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero)) })
                { bi := Setlec.BinderInfo.implicit,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.succ (Setlec.Level.zero))
                           (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))) } }

/-- Annotated standard-shape pin (generated). -/
def choiceA : ConstantVal :=
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Classical") "choice",
      levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
      type := Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "α")
                (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
                (Setlec.Expr.forallE
                  (Setlec.Name.anonymous)
                  (Setlec.Expr.app
                    (Setlec.Expr.const
                      (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty")
                      [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                    (Setlec.Expr.bvar 0))
                  (Setlec.Expr.bvar 1)
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")) })
                { bi := Setlec.BinderInfo.implicit,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.zero)
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))) } }

end Setlec
