import Setlec.Kernel.Basis.Eq

/-!
# Recognized standard axioms and their prerequisite shapes

The lean-inductive-models preprocessor's generated routes may use the
standard axioms `propext` and `Classical.choice`.  Both are true in
the set-theoretic model — `propext` by extensionality of propositions
(derived through the stored `Iff` recursor), `Classical.choice` by
global choice (through the stored `Nonempty` recursor) — so the
checker accepts exactly these two axioms, after pinning their types
and the *shapes of the inductives they quantify over* to what the
preprocessor emits.  Raw pins below; the annotated forms (what the
checker's own annotation produces for them, in dependency order) are
generated by `AnnotateBasis.lean` — do not edit them by hand.
-/

namespace Setlec

open Name (anonymous)

/-- The name `propext`. -/
def propextName : Name := anonymous |>.str "propext"

/-- The name `Classical.choice`. -/
def choiceName : Name := (anonymous |>.str "Classical") |>.str "choice"

/-- The axioms tolerated as *declarations* (dropped by the frontend,
never installed; any use is skipped and taints the run): exactly
`sorryAx` (user ruling).  The `Init` compiler-trust family
(`Lean.trustCompiler`, `Lean.ofReduceNat`, `Lean.ofReduceBool`) is
*installed* instead (task #95, `Setlec/Kernel/TrustAxioms.lean`); any
other non-pinned axiom is a positive decline at its own record. -/
def toleratedAxiomNames : List Name :=
  [ anonymous |>.str "sorryAx" ]

/-- The name `Iff`. -/
def iffName : Name := anonymous |>.str "Iff"

/-- The name `Iff.intro`. -/
def iffIntroName : Name := iffName |>.str "intro"

/-- The name `Iff.rec`. -/
def iffRecName : Name := iffName |>.str "rec"

/-- The name `Nonempty`. -/
def nonemptyName : Name := anonymous |>.str "Nonempty"

/-- The name `Nonempty.intro`. -/
def nonemptyIntroName : Name := nonemptyName |>.str "intro"

/-- The name `Nonempty.rec`. -/
def nonemptyRecName : Name := nonemptyName |>.str "rec"

/-- Erase binder and `fvar` names (annotations preserved): the
standard shapes are pinned up to the exporter's unstable hygienic
binder names, which the interpretation never reads. -/
def Expr.eraseNames : Expr → Expr
  | .bvar i => .bvar i
  | .fvar i _ ty => .fvar i .anonymous ty.eraseNames
  | .sort u => .sort u
  | .const n us => .const n us
  | .app f a => .app f.eraseNames a.eraseNames
  | .lam _ ty b m => .lam .anonymous ty.eraseNames b.eraseNames m
  | .forallE _ ty b m => .forallE .anonymous ty.eraseNames b.eraseNames m
  | .letE _ ty v b => .letE .anonymous ty.eraseNames v.eraseNames
      b.eraseNames
  | .lit l => .lit l
  | .proj s i e => .proj s i e.eraseNames

/-- Shape comparison for the standard pins: exact name, level
parameters and counts, type up to binder names.

**Guidance for anyone adding a pin.**  Two properties of a pin decide
how expensive it is for a *consumer* of the pin (the checker's own
soundness proofs, and the type-theory bridge of task #119):

* **Pin the level when the artifact only ever needs one.**  A pin that
  quantifies a level is more general, and that generality is paid for
  by every consumer: it must supply a level assignment and carry it
  through each application.  Measured instance —
  `Nonempty.rec`'s motive sort is pinned to `Prop` while
  `Iff.rec.{u_1,u}` quantifies its, and the bridge's `Iff` elimination
  needed a bespoke assignment driving `u_1` to `0` where the
  `Nonempty` one needed nothing at all.  *A pin that fixes a level is
  easier to consume than a pin that quantifies one, even when the
  quantified pin is more general.*
* **What this comparison forgives is what the interpretation ignores.**
  `matchesPin` accepts a stored type equal to the pin *up to binder
  names*, and neither the set model's `interpExpr` nor the bridge's
  `denote` reads a binder name — a binder is opened with a variable
  whose meaning is its de Bruijn index.  That alignment is why a
  `matchesPin` hit is usable at all: a consumer may compute on the
  *pin* rather than on whatever spelling the input stream sent.
  Preserve it — a pin comparison must never forgive something the
  interpretation reads. -/
def ConstantVal.matchesPin (cv pin : ConstantVal) : Bool :=
  cv.name = pin.name && cv.levelParams = pin.levelParams &&
    cv.type.eraseNames == pin.type.eraseNames

/-- The raw `Iff` family and `propext`, as the preprocessor emits
them (dependency order). -/
def iffFamily : List ConstantInfo := [
  .indInfo ⟨(anonymous |>.str "Iff"), [], (.forallE (anonymous |>.str "a") (.sort (.zero)) (.forallE (anonymous |>.str "b") (.sort (.zero)) (.sort (.zero)) ⟨.default⟩) ⟨.default⟩)⟩ {},
  .ctorInfo ⟨((anonymous |>.str "Iff") |>.str "intro"), [], (.forallE (anonymous |>.str "a") (.sort (.zero)) (.forallE (anonymous |>.str "b") (.sort (.zero)) (.forallE (anonymous |>.str "mp") (.forallE (anonymous) (.bvar 1) (.bvar 1) ⟨.default⟩) (.forallE (anonymous |>.str "mpr") (.forallE (anonymous) (.bvar 1) (.bvar 3) ⟨.default⟩) (.app (.app (.const (anonymous |>.str "Iff") []) (.bvar 3)) (.bvar 2)) ⟨.default⟩) ⟨.default⟩) ⟨.implicit⟩) ⟨.implicit⟩)⟩ 2 2,
  .recInfo ⟨((anonymous |>.str "Iff") |>.str "rec"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "a") (.sort (.zero)) (.forallE (anonymous |>.str "b") (.sort (.zero)) (.forallE (anonymous |>.str "motive") (.forallE (anonymous |>.str "t") (.app (.app (.const (anonymous |>.str "Iff") []) (.bvar 1)) (.bvar 0)) (.sort (.param (anonymous |>.str "u"))) ⟨.default⟩) (.forallE (anonymous |>.str "intro") (.forallE (anonymous |>.str "mp") (.forallE (anonymous |>.str "right") (.bvar 2) (.bvar 2) ⟨.default⟩) (.forallE (anonymous |>.str "mpr") (.forallE (anonymous) (.bvar 2) (.bvar 4) ⟨.default⟩) (.app (.bvar 2) (.app (.app (.app (.app (.const ((anonymous |>.str "Iff") |>.str "intro") []) (.bvar 4)) (.bvar 3)) (.bvar 1)) (.bvar 0))) ⟨.default⟩) ⟨.default⟩) (.forallE (anonymous |>.str "t") (.app (.app (.const (anonymous |>.str "Iff") []) (.bvar 3)) (.bvar 2)) (.app (.bvar 2) (.bvar 0)) ⟨.default⟩) ⟨.default⟩) ⟨.implicit⟩) ⟨.implicit⟩) ⟨.implicit⟩)⟩ 4 4 []]

/-- The raw `propext` declaration. -/
def propextRaw : ConstantVal := ⟨(anonymous |>.str "propext"), [], (.forallE (anonymous |>.str "a") (.sort (.zero)) (.forallE (anonymous |>.str "b") (.sort (.zero)) (.forallE (anonymous) (.app (.app (.const (anonymous |>.str "Iff") []) (.bvar 1)) (.bvar 0)) (.app (.app (.app (.const (anonymous |>.str "Eq") [(.succ (.zero))]) (.sort (.zero))) (.bvar 2)) (.bvar 1)) ⟨.default⟩) ⟨.implicit⟩) ⟨.implicit⟩)⟩

/-- The raw `Nonempty` family. -/
def nonemptyFamily : List ConstantInfo := [
  .indInfo ⟨(anonymous |>.str "Nonempty"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.sort (.zero)) ⟨.default⟩)⟩ {},
  .ctorInfo ⟨((anonymous |>.str "Nonempty") |>.str "intro"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous |>.str "val") (.bvar 0) (.app (.const (anonymous |>.str "Nonempty") [(.param (anonymous |>.str "u"))]) (.bvar 1)) ⟨.default⟩) ⟨.implicit⟩)⟩ 1 1,
  .recInfo ⟨((anonymous |>.str "Nonempty") |>.str "rec"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous |>.str "motive") (.forallE (anonymous |>.str "t") (.app (.const (anonymous |>.str "Nonempty") [(.param (anonymous |>.str "u"))]) (.bvar 0)) (.sort (.zero)) ⟨.default⟩) (.forallE (anonymous |>.str "intro") (.forallE (anonymous |>.str "val") (.bvar 1) (.app (.bvar 1) (.app (.app (.const ((anonymous |>.str "Nonempty") |>.str "intro") [(.param (anonymous |>.str "u"))]) (.bvar 2)) (.bvar 0))) ⟨.default⟩) (.forallE (anonymous |>.str "t") (.app (.const (anonymous |>.str "Nonempty") [(.param (anonymous |>.str "u"))]) (.bvar 2)) (.app (.bvar 2) (.bvar 0)) ⟨.default⟩) ⟨.default⟩) ⟨.implicit⟩) ⟨.implicit⟩)⟩ 3 3 []]

/-- The raw `Classical.choice` declaration. -/
def choiceRaw : ConstantVal := ⟨((anonymous |>.str "Classical") |>.str "choice"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous) (.app (.const (anonymous |>.str "Nonempty") [(.param (anonymous |>.str "u"))]) (.bvar 0)) (.bvar 1) ⟨.default⟩) ⟨.implicit⟩)⟩

/-- Annotated standard-shape pin (generated). -/
def iffA : ConstantInfo :=
  Setlec.ConstantInfo.indInfo
  { name := Setlec.Name.str (Setlec.Name.anonymous) "Iff",
    levelParams := [],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "a")
              (Setlec.Expr.sort (Setlec.Level.zero))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "b")
                (Setlec.Expr.sort (Setlec.Level.zero))
                (Setlec.Expr.sort (Setlec.Level.zero))
                { bi := Setlec.BinderInfo.default})
              { bi := Setlec.BinderInfo.default} }
  { eta := false,
    etaCtor := Setlec.Name.anonymous,
    etaParams := 0,
    etaFields := 0,
    unitlike := false,
    unitParams := 0,
    ruleK := false }

/-- Annotated standard-shape pin (generated). -/
def iffIntroA : ConstantInfo :=
  Setlec.ConstantInfo.ctorInfo
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Iff") "intro",
    levelParams := [],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "a")
              (Setlec.Expr.sort (Setlec.Level.zero))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "b")
                (Setlec.Expr.sort (Setlec.Level.zero))
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "mp")
                  (Setlec.Expr.forallE
                    (Setlec.Name.anonymous)
                    (Setlec.Expr.bvar 1)
                    (Setlec.Expr.bvar 1)
                    { bi := Setlec.BinderInfo.default})
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "mpr")
                    (Setlec.Expr.forallE
                      (Setlec.Name.anonymous)
                      (Setlec.Expr.bvar 1)
                      (Setlec.Expr.bvar 3)
                      { bi := Setlec.BinderInfo.default})
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Iff") [])
                        (Setlec.Expr.bvar 3))
                      (Setlec.Expr.bvar 2))
                    { bi := Setlec.BinderInfo.default})
                  { bi := Setlec.BinderInfo.default})
                { bi := Setlec.BinderInfo.implicit})
              { bi := Setlec.BinderInfo.implicit} }
  2
  2

/-- Annotated standard-shape pin (generated). -/
def iffRecA : ConstantInfo :=
  Setlec.ConstantInfo.recInfo
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Iff") "rec",
    levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "a")
              (Setlec.Expr.sort (Setlec.Level.zero))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "b")
                (Setlec.Expr.sort (Setlec.Level.zero))
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "motive")
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "t")
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Iff") [])
                        (Setlec.Expr.bvar 1))
                      (Setlec.Expr.bvar 0))
                    (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
                    { bi := Setlec.BinderInfo.default})
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "intro")
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "mp")
                      (Setlec.Expr.forallE
                        (Setlec.Name.str (Setlec.Name.anonymous) "right")
                        (Setlec.Expr.bvar 2)
                        (Setlec.Expr.bvar 2)
                        { bi := Setlec.BinderInfo.default})
                      (Setlec.Expr.forallE
                        (Setlec.Name.str (Setlec.Name.anonymous) "mpr")
                        (Setlec.Expr.forallE
                          (Setlec.Name.anonymous)
                          (Setlec.Expr.bvar 2)
                          (Setlec.Expr.bvar 4)
                          { bi := Setlec.BinderInfo.default})
                        (Setlec.Expr.app
                          (Setlec.Expr.bvar 2)
                          (Setlec.Expr.app
                            (Setlec.Expr.app
                              (Setlec.Expr.app
                                (Setlec.Expr.app
                                  (Setlec.Expr.const
                                    (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Iff") "intro")
                                    [])
                                  (Setlec.Expr.bvar 4))
                                (Setlec.Expr.bvar 3))
                              (Setlec.Expr.bvar 1))
                            (Setlec.Expr.bvar 0)))
                        { bi := Setlec.BinderInfo.default})
                      { bi := Setlec.BinderInfo.default})
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "t")
                      (Setlec.Expr.app
                        (Setlec.Expr.app
                          (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Iff") [])
                          (Setlec.Expr.bvar 3))
                        (Setlec.Expr.bvar 2))
                      (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 0))
                      { bi := Setlec.BinderInfo.default})
                    { bi := Setlec.BinderInfo.default})
                  { bi := Setlec.BinderInfo.implicit})
                { bi := Setlec.BinderInfo.implicit})
              { bi := Setlec.BinderInfo.implicit} }
  4
  4
  []

/-- Annotated standard-shape pin (generated). -/
def nonemptyA : ConstantInfo :=
  Setlec.ConstantInfo.indInfo
  { name := Setlec.Name.str (Setlec.Name.anonymous) "Nonempty",
    levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "α")
              (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
              (Setlec.Expr.sort (Setlec.Level.zero))
              { bi := Setlec.BinderInfo.default} }
  { eta := false,
    etaCtor := Setlec.Name.anonymous,
    etaParams := 0,
    etaFields := 0,
    unitlike := false,
    unitParams := 0,
    ruleK := false }

/-- Annotated standard-shape pin (generated). -/
def nonemptyIntroA : ConstantInfo :=
  Setlec.ConstantInfo.ctorInfo
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty") "intro",
    levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "α")
              (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "val")
                (Setlec.Expr.bvar 0)
                (Setlec.Expr.app
                  (Setlec.Expr.const
                    (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty")
                    [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                  (Setlec.Expr.bvar 1))
                { bi := Setlec.BinderInfo.default})
              { bi := Setlec.BinderInfo.implicit} }
  1
  1

/-- Annotated standard-shape pin (generated). -/
def nonemptyRecA : ConstantInfo :=
  Setlec.ConstantInfo.recInfo
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty") "rec",
    levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "α")
              (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "motive")
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "t")
                  (Setlec.Expr.app
                    (Setlec.Expr.const
                      (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty")
                      [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                    (Setlec.Expr.bvar 0))
                  (Setlec.Expr.sort (Setlec.Level.zero))
                  { bi := Setlec.BinderInfo.default})
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "intro")
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "val")
                    (Setlec.Expr.bvar 1)
                    (Setlec.Expr.app
                      (Setlec.Expr.bvar 1)
                      (Setlec.Expr.app
                        (Setlec.Expr.app
                          (Setlec.Expr.const
                            (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty") "intro")
                            [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                          (Setlec.Expr.bvar 2))
                        (Setlec.Expr.bvar 0)))
                    { bi := Setlec.BinderInfo.default})
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "t")
                    (Setlec.Expr.app
                      (Setlec.Expr.const
                        (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty")
                        [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                      (Setlec.Expr.bvar 2))
                    (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 0))
                    { bi := Setlec.BinderInfo.default})
                  { bi := Setlec.BinderInfo.default})
                { bi := Setlec.BinderInfo.implicit})
              { bi := Setlec.BinderInfo.implicit} }
  3
  3
  []

/-- Annotated standard-shape pin (generated). -/
def propextA : ConstantVal :=
  { name := Setlec.Name.str (Setlec.Name.anonymous) "propext",
      levelParams := [],
      type := Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "a")
                (Setlec.Expr.sort (Setlec.Level.zero))
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "b")
                  (Setlec.Expr.sort (Setlec.Level.zero))
                  (Setlec.Expr.forallE
                    (Setlec.Name.anonymous)
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Iff") [])
                        (Setlec.Expr.bvar 1))
                      (Setlec.Expr.bvar 0))
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.app
                          (Setlec.Expr.const
                            (Setlec.Name.str (Setlec.Name.anonymous) "Eq")
                            [Setlec.Level.succ (Setlec.Level.zero)])
                          (Setlec.Expr.sort (Setlec.Level.zero)))
                        (Setlec.Expr.bvar 2))
                      (Setlec.Expr.bvar 1))
                    { bi := Setlec.BinderInfo.default})
                  { bi := Setlec.BinderInfo.implicit})
                { bi := Setlec.BinderInfo.implicit} }

/-- Annotated standard-shape pin (generated). -/
def choiceA : ConstantVal :=
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Classical") "choice",
      levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
      type := Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "α")
                (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
                (Setlec.Expr.forallE
                  (Setlec.Name.anonymous)
                  (Setlec.Expr.app
                    (Setlec.Expr.const
                      (Setlec.Name.str (Setlec.Name.anonymous) "Nonempty")
                      [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                    (Setlec.Expr.bvar 0))
                  (Setlec.Expr.bvar 1)
                  { bi := Setlec.BinderInfo.default})
                { bi := Setlec.BinderInfo.implicit} }


/-- Is this checked axiom one of the two recognized standard axioms,
over standardly-shaped stored `Iff` / `Nonempty` families (and the
pinned `Eq` basis)?  A pure predicate so the checker's `axiomDecl`
arm stays a single conditional.

**Why all three of the family's constants are pinned, not just the
type.**  The verification has to *realize* the axiom, and the two
spellings differ: the checker's `propext` takes `Iff a b`, while the
declarative layer's takes the two implications separately
(`Setlec/TT/Const.lean`).  Bridging them needs the implications
extracted from the `Iff` — and **nothing in the layer turns an
inhabitant of an opaque family into its fields except that family's own
recursor**, since a modeled inductive is opaque to the interpretation
by design.  So `Iff.rec` (resp. `Nonempty.rec`) has to be pinned
alongside the type, and `Iff.intro` (resp. `Nonempty.intro`) with it,
because the recursor's minor premise is stated at the constructor.
Only the recursors' *types* are used — never their reduction rules
(`Setlec/TTVerify/StdAxiomKey.lean`, and `Setlec/TTVerify/DESIGN.md`
§8.4 for why that distinction carries a scheduling consequence).  The
pins predate that argument; it is recorded here because it is the
reason they are right. -/
def stdAxiomOk (env : Env) (cvA : ConstantVal) : Bool :=
  if cvA.name = propextName then
    decide (env.find? eqName = some eqA) &&
    (match env.find? iffName with
     | some (.indInfo cvI _) => ConstantVal.matchesPin cvI iffA.toConstantVal
     | _ => false) &&
    (match env.find? iffIntroName with
     | some (.ctorInfo cvIi 2 2) =>
       ConstantVal.matchesPin cvIi iffIntroA.toConstantVal
     | _ => false) &&
    (match env.find? iffRecName with
     | some (.recInfo cvIr 4 4 _) =>
       ConstantVal.matchesPin cvIr iffRecA.toConstantVal
     | _ => false) &&
    ConstantVal.matchesPin cvA propextA
  else if cvA.name = choiceName then
    (match env.find? nonemptyName with
     | some (.indInfo cvN _) =>
       ConstantVal.matchesPin cvN nonemptyA.toConstantVal
     | _ => false) &&
    (match env.find? nonemptyIntroName with
     | some (.ctorInfo cvNi 1 1) =>
       ConstantVal.matchesPin cvNi nonemptyIntroA.toConstantVal
     | _ => false) &&
    (match env.find? nonemptyRecName with
     | some (.recInfo cvNr 3 3 _) =>
       ConstantVal.matchesPin cvNr nonemptyRecA.toConstantVal
     | _ => false) &&
    ConstantVal.matchesPin cvA choiceA
  else false

end Setlec
