import Setlec.Kernel.StdAxioms
import Setlec.Kernel.Basis
import Setlec.Kernel.Core
import Setlec.Kernel.TrustPins

/-!
# The compiler-trust axiom family (task #95)

`Init`'s compiler-trust scaffolding is installed instead of
taint-skipped:

* `Lean.trustCompiler : True` is trivially realizable — it is
  installed as an *opaque* (stored `thmInfo`, exactly like a checked
  `opaque` declaration) with value `True.intro`, over a pinned `True`
  family.  No new meta-axiom: the model is `True.intro`'s own
  interpretation.
* `Lean.reduceNat` / `Lean.reduceBool` then check as ordinary
  `opaque`s (their exported values are identity functions modulo the
  `have := trustCompiler` wrapper); at install their stored values are
  pinned against the toolchain's own definitions
  (`Setlec/Kernel/TrustPins.lean`, generated at build time) by
  definitional equality — the task-#47 pattern: drift declines,
  never silently.
* `Lean.ofReduceNat` / `Lean.ofReduceBool` are pinned axioms over
  those stored opaques (the task-#34 standard-axioms machinery).  With
  the stored reduce operation certified to be the identity (a
  definitional-equality certificate at the axiom's own install,
  `checkOfReduceAx`), `∀ a b, reduceNat a = b → a = b` interprets to
  an inhabited proposition (the hypothesis *is* the conclusion), so
  both axioms are true in the set model with the proof point as value.

`sorryAx` remains the only tolerated (skip-taint) axiom.

Raw pins below; the annotated forms are generated by
`AnnotateBasis.lean` — do not edit them by hand.
-/

namespace Setlec

open Name (anonymous)

/-- The name `True`. -/
def trueName : Name := anonymous |>.str "True"

/-- The name `True.intro`. -/
def trueIntroName : Name := trueName |>.str "intro"

/-- The name `Lean.trustCompiler`. -/
def trustCompilerName : Name := (anonymous |>.str "Lean") |>.str "trustCompiler"

/-- The name `Lean.reduceNat`. -/
def reduceNatName : Name := (anonymous |>.str "Lean") |>.str "reduceNat"

/-- The name `Lean.reduceBool`. -/
def reduceBoolName : Name := (anonymous |>.str "Lean") |>.str "reduceBool"

/-- The name `Lean.ofReduceNat`. -/
def ofReduceNatName : Name := (anonymous |>.str "Lean") |>.str "ofReduceNat"

/-- The name `Lean.ofReduceBool`. -/
def ofReduceBoolName : Name := (anonymous |>.str "Lean") |>.str "ofReduceBool"

/-- The reduce operations pinned at their `opaque` install. -/
def reduceOpNames : List Name := [reduceNatName, reduceBoolName]

/-- The reduce operation an `ofReduce*` axiom speaks about. -/
def ofReduceOp (n : Name) : Name :=
  if n = ofReduceNatName then reduceNatName else reduceBoolName

/-! ## Pinned shapes

The `True` family, `Bool`, and the reduce operations' types have no
binders below a codomain (or none at all), so their annotated forms
coincide with the raw pins except for the one codomain annotation on
`… → …`; the `ofReduce*` types are annotated by `AnnotateBasis.lean`.
-/

/-- Pinned `True` (shape only; capabilities are not pinned). -/
def trueCvA : ConstantVal := ⟨trueName, [], .sort .zero⟩

/-- Pinned `True.intro`. -/
def trueIntroCvA : ConstantVal := ⟨trueIntroName, [], .const trueName []⟩

/-- Pinned `Lean.trustCompiler`. -/
def trustCompilerA : ConstantVal := ⟨trustCompilerName, [], .const trueName []⟩

/-- The realizability witness of the installed `Lean.trustCompiler`:
`True.intro` (a constant is its own annotated form).  Not stored —
opaques are stored as `axiomInfo` — but the model interprets the
constant by this value's interpretation. -/
def trustCompilerValueA : Expr := .const trueIntroName []

/-- Pinned `Bool` (shape only). -/
def boolCvA : ConstantVal := ⟨boolName, [], .sort (.succ .zero)⟩

/-- The element inductive of a reduce operation. -/
def reduceElemName (c : Name) : Name :=
  if c = reduceNatName then natName else boolName

/-- The element type of a reduce operation, as the pinned constant. -/
def reduceElemTy (c : Name) : Expr :=
  if c = reduceNatName then .const natName [] else .const boolName []

/-- Raw pinned type of `Lean.reduceNat` / `Lean.reduceBool`. -/
def reduceOpRaw (c : Name) : ConstantVal :=
  ⟨c, [], .forallE (anonymous |>.str "n") (reduceElemTy c) (reduceElemTy c)
    ⟨.default, .never⟩⟩

/-- Raw pinned type of `Lean.ofReduceNat` / `Lean.ofReduceBool`:
`∀ (a b : τ), reduce a = b → a = b` at `τ = Nat` / `Bool`. -/
def ofReduceRaw (n : Name) : ConstantVal :=
  let c := ofReduceOp n
  let τ := reduceElemTy c
  let eqApp : Expr → Expr → Expr := fun x y =>
    .app (.app (.app (.const eqName [.succ .zero]) τ) x) y
  ⟨n, [], .forallE (anonymous |>.str "a") τ
    (.forallE (anonymous |>.str "b") τ
      (.forallE (anonymous |>.str "h")
        (eqApp (.app (.const c []) (.bvar 1)) (.bvar 0))
        (eqApp (.bvar 2) (.bvar 1))
        ⟨.default, .never⟩)
      ⟨.default, .never⟩)
    ⟨.default, .never⟩⟩

/-- Annotated standard-shape pin (generated). -/
def reduceNatCvA : ConstantVal :=
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Lean") "reduceNat",
    levelParams := [],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "n")
              (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
              (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
              { bi := Setlec.BinderInfo.default, pw := Setlec.PropWhen.never } }

/-- Annotated standard-shape pin (generated). -/
def reduceBoolCvA : ConstantVal :=
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Lean") "reduceBool",
    levelParams := [],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "n")
              (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Bool") [])
              (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Bool") [])
              { bi := Setlec.BinderInfo.default, pw := Setlec.PropWhen.never } }

/-- Annotated standard-shape pin (generated). -/
def ofReduceNatA : ConstantVal :=
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Lean") "ofReduceNat",
    levelParams := [],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "a")
              (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "b")
                (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "h")
                  (Setlec.Expr.app
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.const
                          (Setlec.Name.str (Setlec.Name.anonymous) "Eq")
                          [Setlec.Level.succ (Setlec.Level.zero)])
                        (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") []))
                      (Setlec.Expr.app
                        (Setlec.Expr.const
                          (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Lean") "reduceNat")
                          [])
                        (Setlec.Expr.bvar 1)))
                    (Setlec.Expr.bvar 0))
                  (Setlec.Expr.app
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.const
                          (Setlec.Name.str (Setlec.Name.anonymous) "Eq")
                          [Setlec.Level.succ (Setlec.Level.zero)])
                        (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") []))
                      (Setlec.Expr.bvar 2))
                    (Setlec.Expr.bvar 1))
                  { bi := Setlec.BinderInfo.default, pw := Setlec.PropWhen.ifAllZero [] })
                { bi := Setlec.BinderInfo.default, pw := Setlec.PropWhen.ifAllZero [] })
              { bi := Setlec.BinderInfo.default, pw := Setlec.PropWhen.ifAllZero [] } }

/-- Annotated standard-shape pin (generated). -/
def ofReduceBoolA : ConstantVal :=
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Lean") "ofReduceBool",
    levelParams := [],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "a")
              (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Bool") [])
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "b")
                (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Bool") [])
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "h")
                  (Setlec.Expr.app
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.const
                          (Setlec.Name.str (Setlec.Name.anonymous) "Eq")
                          [Setlec.Level.succ (Setlec.Level.zero)])
                        (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Bool") []))
                      (Setlec.Expr.app
                        (Setlec.Expr.const
                          (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Lean") "reduceBool")
                          [])
                        (Setlec.Expr.bvar 1)))
                    (Setlec.Expr.bvar 0))
                  (Setlec.Expr.app
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.const
                          (Setlec.Name.str (Setlec.Name.anonymous) "Eq")
                          [Setlec.Level.succ (Setlec.Level.zero)])
                        (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Bool") []))
                      (Setlec.Expr.bvar 2))
                    (Setlec.Expr.bvar 1))
                  { bi := Setlec.BinderInfo.default, pw := Setlec.PropWhen.ifAllZero [] })
                { bi := Setlec.BinderInfo.default, pw := Setlec.PropWhen.ifAllZero [] })
              { bi := Setlec.BinderInfo.default, pw := Setlec.PropWhen.ifAllZero [] } }

/-- The annotated pinned type of a reduce operation. -/
def reduceOpCvA (c : Name) : ConstantVal :=
  if c = reduceNatName then reduceNatCvA else reduceBoolCvA

/-- The annotated pin an `ofReduce*` axiom is matched against. -/
def ofReducePinA (n : Name) : ConstantVal :=
  if n = ofReduceNatName then ofReduceNatA else ofReduceBoolA

/-! ## Environment predicates -/

/-- Is `Lean.trustCompiler` installable here?  The `True` family must
be stored with the pinned shapes (so the synthesized value
`True.intro` resolves and inhabits the pinned type), and the checked
axiom's type must match the pin. -/
def trustCompilerOk (env : Env) (cvA : ConstantVal) : Bool :=
  (match env.find? trueName with
   | some (.indInfo cvT _) => ConstantVal.matchesPin cvT trueCvA
   | _ => false) &&
  (match env.find? trueIntroName with
   | some (.ctorInfo cvTi 0 0) => ConstantVal.matchesPin cvTi trueIntroCvA
   | _ => false) &&
  ConstantVal.matchesPin cvA trustCompilerA

/-- Is the reduce operation `c` stored as a checked opaque
(`axiomInfo`, the storage kind of every checked `opaque`) of the
pinned type? -/
def reduceStoredOk (env : Env) (c : Name) : Bool :=
  match env.find? c with
  | some (.axiomInfo cvR) => ConstantVal.matchesPin cvR (reduceOpCvA c)
  | _ => false

/-- The element-inductive shape an `ofReduce*` axiom needs: the pinned
`Nat` basis resp. a standardly-shaped stored `Bool`. -/
def reduceElemOk (env : Env) (c : Name) : Bool :=
  if c = reduceNatName then decide (env.find? natName = some natA)
  else
    match env.find? boolName with
    | some (.indInfo cvB _) => ConstantVal.matchesPin cvB boolCvA
    | _ => false

/-- Is this checked axiom a pinned `ofReduce*` over a standardly-shaped
environment?  Requires the pinned `Eq` basis (the type is an equality
implication), the element inductive, and the reduce operation stored
as a pinned opaque — whose install already ran the identity
certificate (`checkReducePin`), the fact the model consumes here. -/
def ofReduceAxOk (env : Env) (cvA : ConstantVal) : Bool :=
  let c := ofReduceOp cvA.name
  decide (env.find? eqName = some eqA) &&
  reduceElemOk env c &&
  reduceStoredOk env c &&
  ConstantVal.matchesPin cvA (ofReducePinA cvA.name)

/-! ## The reduce-operation install pin -/

/-- The pinned defining expression of a reduce operation
(`Setlec/Kernel/TrustPins.lean`, generated at build time from the
toolchain's own prelude; the `have := trustCompiler` wrapper is
zeta-expanded by the generator, leaving the plain identity). -/
def reduceDeclPin (c : Name) : Expr :=
  if c = reduceNatName then reduceNatDeclPin else reduceBoolDeclPin

/-- Syntactic guards on the generated pin (checked once at install). -/
def reducePinGuard (env : Env) (c : Name) : Bool :=
  (reduceDeclPin c).looseBVarsBounded 0 && !(reduceDeclPin c).hasFvar &&
  (reduceDeclPin c).allLevelParamsDefined [] &&
  (reduceDeclPin c).constsResolve env

/-- The identity certificate's variable: `fvar 0` at the element
type. -/
def reduceCertVar (c : Name) : Expr :=
  .fvar 0 (anonymous |>.str "a") (reduceElemTy c)

end Setlec
