import Setlec.SetR.Rel
import Setlec.SetR.ProjPins
import Setlec.SetR.AnnotOkV
import Setlec.SetR.Sound.Motives
import Setlec.SetR.Sound.Struct
import Setlec.SetR.Sound.Irrel
import Setlec.SetR.Sound.Rigidity
import Setlec.SetR.Sound.Stuck
import Setlec.SetR.Sound.Proj
import Setlec.SetR.Sound.Lit
import Setlec.SetR.Sound.NatOps
import Setlec.SetR.Sound.NatOpsWf
import Setlec.SetR.Sound.Iota
import Setlec.SetR.Sound.Main
import Setlec.SetR.Weaken
import Setlec.SetR.CtxOkR
import Setlec.SetR.Decl
import Setlec.SetR.EnvS
import Setlec.SetR.Install.Cons
import Setlec.SetR.Install.Value
import Setlec.SetR.Install.ValueKinds
import Setlec.SetR.Install.Axiom
import Setlec.SetR.Install.ReducePin
import Setlec.SetR.Install.IndBottomS
import Setlec.SetR.Install.IndFrameS
import Setlec.SetR.Install.IndStagesS
import Setlec.SetR.Install.IndBottomPlainS
import Setlec.SetR.Install.IndNestedS
import Setlec.SetR.Install.IndBottomNestedS
import Setlec.SetR.Install.IndBottomProjS
import Setlec.SetR.Install.EtaLawS
import Setlec.SetR.Install.Step
import Setlec.SetR.Install.IndMemberS
import Setlec.SetR.Install.IndMembersS
import Setlec.SetR.Install.SwapS
import Setlec.SetR.Install.IotaRuleS
import Setlec.SetR.Install.IndRecsS
import Setlec.SetR.Install.ProjInstallS
import Setlec.SetR.Install.DeclIndS
import Setlec.SetR.Install.BasisS
import Setlec.SetR.Examples
import Setlec.SetR.Bridge.Env
import Setlec.SetR.Bridge.Claims
import Setlec.SetR.Bridge.WhnfCore
import Setlec.SetR.Bridge.Infer
import Setlec.SetR.Bridge.DefEq
import Setlec.SetR.Bridge.ReduceNat
import Setlec.SetR.Bridge.InferStruct
import Setlec.SetR.Bridge.Spine
import Setlec.SetR.Bridge.Irrel
import Setlec.SetR.Bridge.Certs
import Setlec.SetR.Bridge.StuckIrrel
import Setlec.SetR.Bridge.Eta
import Setlec.SetR.Bridge.StrLitR
import Setlec.SetR.Bridge.Stuck
import Setlec.SetR.Bridge.EtaCerts
import Setlec.SetR.Bridge.DefEqClosed
import Setlec.SetR.Bridge.Proj
import Setlec.SetR.Bridge.ProjRed
import Setlec.SetR.Bridge.Major
import Setlec.SetR.Bridge.Iota
import Setlec.SetR.Bridge.Main
import Setlec.SetR.Bridge.Decl
import Setlec.SetR.Bridge.DeclInd
import Setlec.SetR.Bridge.Sound
import Setlec.SetR.Main
import Setlec.SetR.Annot.Syntax
import Setlec.SetR.Annot.Pass
import Setlec.SetR.Annot.Kinding
import Setlec.SetR.Annot.Validity
import Setlec.SetR.Interp2.Univ
import Setlec.SetR.Interp2.TierA
import Setlec.SetR.Interp2.Graded
import Setlec.SetR.Interp2.Pilot
import Setlec.SetR.Annot.Ok2
import Setlec.SetR.Annot.Spine2
import Setlec.SetR.Annot.EnvS2
import Setlec.SetR.Annot.Canon
import Setlec.SetR.Annot.SimSubst
import Setlec.SetR.Annot.PremiseLadder
import Setlec.SetR.Annot.SortCoh
import Setlec.SetR.DivModPin
import Setlec.SetR.StdAxiomKey

/-!
# `Setlec.SetR` — umbrella for the task-#148 relation family

See `Setlec/SetR/DESIGN.md` for the campaign section,
`Setlec/SetR/Rel.lean` for the family itself and
`Setlec/SetR/Bridge/*.lean` for the checker-to-derivation bridge.
-/
