import Setlec.SetBase.Rel
import Setlec.SetBase.ProjPins
import Setlec.SetR.AnnotOkV
import Setlec.SetR.Sound.Motives
import Setlec.SetR.Sound.Struct
import Setlec.SetR.Sound.Irrel
import Setlec.SetR.Sound.Rigidity
import Setlec.SetR.Sound.Stuck
import Setlec.SetR.Sound.Proj
import Setlec.SetR.Sound.Lit
import Setlec.SetR.Sound.NatOps
import Setlec.SetR.Sound.NatOpsWf
import Setlec.SetR.Sound.Iota
import Setlec.SetR.Sound.Main
import Setlec.SetBase.Weaken
import Setlec.SetBase.CtxOkR
import Setlec.SetBase.Decl
import Setlec.SetR.EnvS
import Setlec.SetR.Install.Cons
import Setlec.SetR.Install.Value
import Setlec.SetR.Install.ValueKinds
import Setlec.SetR.Install.Axiom
import Setlec.SetR.Install.ReducePin
import Setlec.SetR.Install.IndBottomS
import Setlec.SetR.Install.IndFrameS
import Setlec.SetR.Install.IndStagesS
import Setlec.SetR.Install.IndBottomPlainS
import Setlec.SetR.Install.IndNestedS
import Setlec.SetR.Install.IndBottomNestedS
import Setlec.SetR.Install.IndBottomProjS
import Setlec.SetR.Install.EtaLawS
import Setlec.SetR.Install.Step
import Setlec.SetR.Install.IndMemberS
import Setlec.SetR.Install.IndMembersS
import Setlec.SetR.Install.SwapS
import Setlec.SetR.Install.IotaRuleS
import Setlec.SetR.Install.IndRecsS
import Setlec.SetR.Install.ProjInstallS
import Setlec.SetR.Install.DeclIndS
import Setlec.SetR.Install.BasisS
import Setlec.SetR.Examples
import Setlec.SetBase.EnvR
import Setlec.SetR.Bridge.Decl
import Setlec.SetR.Bridge.Sound
import Setlec.SetR.Main
import Setlec.SetR.Main2
import Setlec.SetR.Annot.Pass
import Setlec.SetR.Annot.Kinding
import Setlec.SetR.Annot.Validity
import Setlec.SetBase.Univ
import Setlec.SetR.Interp2.TierA
import Setlec.SetR.Interp2.Graded
import Setlec.SetR.Interp2.Pilot
import Setlec.SetBase.Spine2
import Setlec.SetR.Annot.EnvS2
import Setlec.SetBase.BasisType
import Setlec.SetBase.BasisOk
import Setlec.SetBase.Skeleton
import Setlec.SetR.Interp2.Claims2
import Setlec.SetR.Interp2.Step2.Infer
import Setlec.SetR.Interp2.Step2.WhnfCore
import Setlec.SetR.Interp2.Step2.Loop
import Setlec.SetBase.LitStep2
import Setlec.SetR.Interp2.Step2.StrLit
import Setlec.SetR.Interp2.Step2.Dispatch
import Setlec.SetR.Interp2.Step2.Routed
import Setlec.SetR.Interp2.Step2.Levels
import Setlec.SetR.Interp2.Step2.LevelsInst
import Setlec.SetR.Interp2.Step2.Whnf
import Setlec.SetR.Interp2.Step2.DefEqRun
import Setlec.SetR.Interp2.Step2.Fuel
import Setlec.SetR.Interp2.Step2.InferQ
import Setlec.SetR.Interp2.Step2.CtxOk2RRefute
import Setlec.SetR.Interp2.Step2.CtxOk2OpenD
import Setlec.SetR.Interp2.Claims2A
import Setlec.SetR.Interp2.EnvS2Refute
import Setlec.SetR.Interp2.Claims2B
import Setlec.SetR.Interp2.Claims2C
import Setlec.SetR.Interp2.CtxOk2D
import Setlec.SetR.Interp2.Step2.SeamMono
import Setlec.SetR.Interp2.Claims2D
import Setlec.SetR.Interp2.Claims2E
import Setlec.SetR.Annot.EnvS2U
import Setlec.SetR.Interp2.EnvS2U
import Setlec.SetR.Interp2.EnvS2UNe
import Setlec.SetR.Interp2.Claims2U
import Setlec.SetR.Interp2.EnvS2UPi
import Setlec.SetR.Interp2.EnvS2UDef
import Setlec.SetR.Interp2.Keys2
import Setlec.SetR.Interp2.Denote2Extend
import Setlec.SetR.Interp2.Keys2Probe
import Setlec.SetR.Interp2.Keys2Cond
import Setlec.SetR.Interp2.Keys2Bundle
import Setlec.SetR.Interp2.EmptyPin2
import Setlec.SetBase.Denote2Closed
import Setlec.SetR.Interp2.Step2Cons
import Setlec.SetR.Interp2.LevelLocal
import Setlec.SetR.Interp2.IotaArity
import Setlec.SetR.Interp2.EnvLaws2
import Setlec.SetR.Interp2.Capstone2C
import Setlec.SetR.Interp2.Capstone2D
import Setlec.SetR.Interp2.Dual2E
import Setlec.SetR.Interp2.Capstone2E
import Setlec.SetR.Interp2.Capstone
import Setlec.SetBase.Install2
import Setlec.SetBase.Canon
import Setlec.SetR.Annot.SimSubst
import Setlec.SetR.Annot.PremiseLadder
import Setlec.SetR.Annot.SortCoh
import Setlec.SetR.Annot.SortCohFrame
import Setlec.SetR.DivModPin
import Setlec.SetR.StdAxiomKey

/-!
# `Setlec.SetR` — umbrella for the task-#148 relation family

See `Setlec/SetR/DESIGN.md` for the campaign section,
`Setlec/SetR/Rel.lean` for the family itself and
`Setlec/SetR/Bridge/*.lean` for the checker-to-derivation bridge.
-/
