import Setlec.SetR.Rel
import Setlec.SetR.ProjPins
import Setlec.SetR.AnnotOkV
import Setlec.SetR.Sound.Motives
import Setlec.SetR.Sound.Struct
import Setlec.SetR.Sound.Irrel
import Setlec.SetR.Sound.Rigidity
import Setlec.SetR.Sound.Stuck
import Setlec.SetR.Sound.Proj
import Setlec.SetR.Sound.Lit
import Setlec.SetR.Sound.NatOps
import Setlec.SetR.Sound.NatOpsWf
import Setlec.SetR.Sound.Iota
import Setlec.SetR.Sound.Main
import Setlec.SetR.Weaken
import Setlec.SetR.CtxOkR
import Setlec.SetR.Decl
import Setlec.SetR.EnvS
import Setlec.SetR.Install.Cons
import Setlec.SetR.Install.Value
import Setlec.SetR.Install.ValueKinds
import Setlec.SetR.Install.Axiom
import Setlec.SetR.Install.ReducePin
import Setlec.SetR.Install.IndBottomS
import Setlec.SetR.Install.IndFrameS
import Setlec.SetR.Install.IndStagesS
import Setlec.SetR.Install.IndBottomPlainS
import Setlec.SetR.Install.IndNestedS
import Setlec.SetR.Install.IndBottomNestedS
import Setlec.SetR.Install.IndBottomProjS
import Setlec.SetR.Install.EtaLawS
import Setlec.SetR.Install.Step
import Setlec.SetR.Install.IndMemberS
import Setlec.SetR.Install.IndMembersS
import Setlec.SetR.Install.SwapS
import Setlec.SetR.Install.IotaRuleS
import Setlec.SetR.Install.IndRecsS
import Setlec.SetR.Install.ProjInstallS
import Setlec.SetR.Install.DeclIndS
import Setlec.SetR.Install.BasisS
import Setlec.SetR.Examples
import Setlec.SetR.Bridge.Env
import Setlec.SetR.Bridge.Claims
import Setlec.SetR.Bridge.WhnfCore
import Setlec.SetR.Bridge.Infer
import Setlec.SetR.Bridge.DefEq
import Setlec.SetR.Bridge.ReduceNat
import Setlec.SetR.Bridge.InferStruct
import Setlec.SetR.Bridge.Spine
import Setlec.SetR.Bridge.Irrel
import Setlec.SetR.Bridge.Certs
import Setlec.SetR.Bridge.StuckIrrel
import Setlec.SetR.Bridge.Eta
import Setlec.SetR.Bridge.StrLitR
import Setlec.SetR.Bridge.Stuck
import Setlec.SetR.Bridge.EtaCerts
import Setlec.SetR.Bridge.DefEqClosed
import Setlec.SetR.Bridge.Proj
import Setlec.SetR.Bridge.ProjRed
import Setlec.SetR.Bridge.Major
import Setlec.SetR.Bridge.Iota
import Setlec.SetR.Bridge.Main
import Setlec.SetR.Bridge.Decl
import Setlec.SetR.Bridge.DeclInd
import Setlec.SetR.Bridge.Sound
import Setlec.SetR.Main
import Setlec.SetR.Main2
import Setlec.SetR.Annot.Syntax
import Setlec.SetR.Annot.Pass
import Setlec.SetR.Annot.Kinding
import Setlec.SetR.Annot.Validity
import Setlec.SetR.Interp2.Univ
import Setlec.SetR.Interp2.TierA
import Setlec.SetR.Interp2.Graded
import Setlec.SetR.Interp2.Pilot
import Setlec.SetR.Annot.Ok2
import Setlec.SetR.Annot.Spine2
import Setlec.SetR.Annot.EnvS2
import Setlec.SetR.Interp2.BasisType
import Setlec.SetR.Interp2.BasisOk
import Setlec.SetR.Interp2.Skeleton
import Setlec.SetR.Interp2.Claims2
import Setlec.SetR.Interp2.Step2.Infer
import Setlec.SetR.Interp2.Step2.WhnfCore
import Setlec.SetR.Interp2.Step2.DefEq
import Setlec.SetR.Interp2.Step2.Loop
import Setlec.SetR.Interp2.Step2.Lit
import Setlec.SetR.Interp2.Step2.StrLit
import Setlec.SetR.Interp2.Step2.Dispatch
import Setlec.SetR.Interp2.Step2.Routed
import Setlec.SetR.Interp2.Step2.Levels
import Setlec.SetR.Interp2.Step2.LevelsInst
import Setlec.SetR.Interp2.Step2.Whnf
import Setlec.SetR.Interp2.Step2.DefEqRun
import Setlec.SetR.Interp2.Step2.Fuel
import Setlec.SetR.Interp2.Step2.InferQ
import Setlec.SetR.Interp2.Step2.CtxOk2RRefute
import Setlec.SetR.Interp2.Step2.CtxOk2OpenD
import Setlec.SetR.Interp2.Claims2A
import Setlec.SetR.Interp2.EnvS2Refute
import Setlec.SetR.Interp2.Claims2B
import Setlec.SetR.Interp2.Claims2C
import Setlec.SetR.Interp2.CtxOk2D
import Setlec.SetR.Interp2.Step2.SeamMono
import Setlec.SetR.Interp2.Claims2D
import Setlec.SetR.Interp2.Claims2E
import Setlec.SetR.Interp2.Claims2P
import Setlec.SetR.Interp2.OkPTransport
import Setlec.SetR.Interp2.CtxOkPKit
import Setlec.SetR.Interp2.Step2.InferP
import Setlec.SetR.Interp2.Step2.WhnfP
import Setlec.SetR.Interp2.Step2.DefEqP
import Setlec.SetR.Interp2.Step2.AssemblyP
import Setlec.SetR.Annot.EnvS2Core
import Setlec.SetR.Annot.EnvS2P
import Setlec.SetR.Interp2.Step2.IrrelP
import Setlec.SetR.Interp2.Step2.StuckP
import Setlec.SetR.Interp2.Step2.ReadsP
import Setlec.SetR.Interp2.Step2.AcceptedP
import Setlec.SetR.Interp2.Step2.NatP
import Setlec.SetR.Interp2.Step2.CapsRowsP
import Setlec.SetR.Interp2.Step2.TiersP
import Setlec.SetR.Interp2.InstallP
import Setlec.SetR.Interp2.NatEqsP
import Setlec.SetR.Interp2.NatSemP
import Setlec.SetR.Interp2.CapsP
import Setlec.SetR.Interp2.DivModP
import Setlec.SetR.Interp2.NatWfP
import Setlec.SetR.Interp2.NatStepP
import Setlec.SetR.Interp2.DivModCertP
import Setlec.SetR.Interp2.CapstoneP
import Setlec.SetR.Interp2.AxiomBitsP
import Setlec.SetR.Interp2.BasisConsP
import Setlec.SetR.Interp2.BitAgree
import Setlec.SetR.Interp2.BasisTypeOk
import Setlec.SetR.Interp2.EqTowerP
import Setlec.SetR.Interp2.BasisStepP
import Setlec.SetR.Interp2.BasisEmptyP
import Setlec.SetR.Interp2.LevelsP
import Setlec.SetR.Interp2.BasisBlocksP
import Setlec.SetR.Interp2.BasisQuotP
import Setlec.SetR.Interp2.BasisEqP
import Setlec.SetR.Interp2.BasisPSigmaP
import Setlec.SetR.Interp2.IndConsP
import Setlec.SetR.Interp2.IndMemberP
import Setlec.SetR.Interp2.IndCapsP
import Setlec.SetR.Interp2.IndMembersP
import Setlec.SetR.Interp2.IndTeleP
import Setlec.SetR.Interp2.IndUnitLawP
import Setlec.SetR.Interp2.IndEtaLawP
import Setlec.SetR.Interp2.IndFrameP
import Setlec.SetR.Interp2.IndProjCapsP
import Setlec.SetR.Interp2.IndProjEtaP
import Setlec.SetR.Interp2.IndRunsP
import Setlec.SetR.Interp2.IndSubstP
import Setlec.SetR.Interp2.IndStageKitP
import Setlec.SetR.Interp2.IndCrossP
import Setlec.SetR.Interp2.IndZipFieldP
import Setlec.SetR.Interp2.IndRenameP
import Setlec.SetR.Interp2.IndGradeP
import Setlec.SetR.Interp2.IndDomGradeP
import Setlec.SetR.Interp2.IndPrefixGradeP
import Setlec.SetR.Interp2.IndParamGradeP
import Setlec.SetR.Interp2.IndFieldGradeP
import Setlec.SetR.Interp2.IndPlainParamP
import Setlec.SetR.Interp2.IndZipperP
import Setlec.SetR.Interp2.IndPointKitP
import Setlec.SetR.Interp2.IndPointP
import Setlec.SetR.Interp2.IndTowerReadP
import Setlec.SetR.Interp2.IndReductP
import Setlec.SetR.Interp2.IndLamTowerP
import Setlec.SetR.Interp2.IndAnnotKitP
import Setlec.SetR.Interp2.IndAnnotMemP
import Setlec.SetR.Interp2.IndFireP
import Setlec.SetR.Interp2.IndTransportP
import Setlec.SetR.Interp2.IndOpenRevP
import Setlec.SetR.Interp2.IndPinGradeP
import Setlec.SetR.Interp2.IndBottomPlainP
import Setlec.SetR.Interp2.IndOpenerGradeP
import Setlec.SetR.Interp2.IndNestedParamP
import Setlec.SetR.Interp2.IndBottomNestedP
import Setlec.SetR.Annot.BitReads
import Setlec.SetR.Interp2.IndPinRowP
import Setlec.SetR.Interp2.IndProjKitP
import Setlec.SetR.Interp2.IndBottomProjP
import Setlec.SetR.Interp2.IotaRulePlainP
import Setlec.SetR.Interp2.IotaRuleNestedP
import Setlec.SetR.Interp2.SwapP
import Setlec.SetR.Interp2.IndPinProbeP
import Setlec.SetR.Interp2.AxiomPinP
import Setlec.SetR.Interp2.HarvestP
import Setlec.SetR.Interp2.FoldP
import Setlec.SetR.Annot.EnvS2U
import Setlec.SetR.Interp2.EnvS2U
import Setlec.SetR.Interp2.EnvS2UNe
import Setlec.SetR.Interp2.Claims2U
import Setlec.SetR.Interp2.EnvS2UPi
import Setlec.SetR.Interp2.EnvS2UDef
import Setlec.SetR.Interp2.Keys2
import Setlec.SetR.Interp2.Denote2Extend
import Setlec.SetR.Interp2.Keys2Probe
import Setlec.SetR.Interp2.Keys2Cond
import Setlec.SetR.Interp2.Keys2Bundle
import Setlec.SetR.Interp2.EmptyPin2
import Setlec.SetR.Interp2.Denote2Closed
import Setlec.SetR.Interp2.Step2Cons
import Setlec.SetR.Interp2.LevelLocal
import Setlec.SetR.Interp2.IotaArity
import Setlec.SetR.Interp2.EnvLaws2
import Setlec.SetR.Interp2.Capstone2C
import Setlec.SetR.Interp2.Capstone2D
import Setlec.SetR.Interp2.Dual2E
import Setlec.SetR.Interp2.Capstone2E
import Setlec.SetR.Interp2.Capstone
import Setlec.SetR.Interp2.Install2
import Setlec.SetR.Annot.Canon
import Setlec.SetR.Annot.Bit
import Setlec.SetR.Annot.BitLemmas
import Setlec.SetR.Annot.BitShift
import Setlec.SetR.Annot.BitInst
import Setlec.SetR.Annot.BitClosed
import Setlec.SetR.Annot.BitInstall
import Setlec.SetR.Annot.BitExtend
import Setlec.SetR.Annot.ValidV
import Setlec.SetR.Annot.ValidVSpine
import Setlec.SetR.Interp2.Step2.BitLevels
import Setlec.SetR.Annot.SimSubst
import Setlec.SetR.Annot.PremiseLadder
import Setlec.SetR.Annot.SortCoh
import Setlec.SetR.Annot.SortCohFrame
import Setlec.SetR.DivModPin
import Setlec.SetR.StdAxiomKey

/-!
# `Setlec.SetR` — umbrella for the task-#148 relation family

See `Setlec/SetR/DESIGN.md` for the campaign section,
`Setlec/SetR/Rel.lean` for the family itself and
`Setlec/SetR/Bridge/*.lean` for the checker-to-derivation bridge.
-/
