module

public import ConLeche.Kernel.StdAxioms
public import ConLeche.Kernel.TypeChecker
public import ConLeche.Kernel.NatOpPins
public import ConLeche.Kernel.Inductives.StructParts

@[expose] public section

/-!
# The declaration checker's common ground

The core entry-point record (`CheckerOps`) with its pure and memoized
instantiations, the common per-declaration constant check
(`checkConstantVal`), and the small strategy-independent helpers the
install paths share (`openPisAtFvars`, `unwrapOr`, `piResultSort`).
The modeled-inductive install builds on this in
`ConLeche/Kernel/Inductives/Modeled.lean` (which also holds the
helpers only it uses: the iota/projection certificate walkers
`checkTypedList`/`checkAnnotList`/`checkDefEqList`, `domsMatchAux`,
`checkProjShape`/`checkProjRule`), everything else in
`ConLeche/Kernel/Checker.lean`.
-/

namespace ConLeche

/-- The core entry points the declaration checker runs on: the checker
is written once against this record, monad-polymorphically, and
instantiated with the pure knot (`fueledOps`/`pureOps`, the
verification's subject) and, in `ConLeche/Cached/CheckerC.lean`, with the
memoized cached knot the binary executes. -/
structure CheckerOps (m : Type → Type) where
  annotate : Env → Nat → Expr → m Expr
  inferType : Env → Nat → Expr → m Expr
  isDefEq : Env → Nat → Expr → Expr → m Bool
  ensureSort : Env → Nat → Expr → m Level
  whnf : Env → Nat → Expr → m Expr
  /-- **The variant-fallback combinator** (task #273).  Run the
  attempt; on `true` the whole is `pure ()`; on `false` OR ON AN ERROR
  the continuation runs.  The only place the checker recovers from a
  thrown error, and it is scoped to the Nat-op pin gate's per-variant
  attempt (`checkDivModPinAt`: one pin variant's defeq comparison and
  certificate check), where a variant generated by another toolchain
  can leave a certificate blob ill-typed — that is "this variant does
  not match", not a checker bug.  The continuation is told the outcome
  (`none` after `false`, `some e` after an error) **for diagnostic text
  only**; the pure instantiations (`fueledOps`, the fueled families of
  the verification tier) hand it `none` regardless — a fuel-indexed
  family is monotone in its *success* and cannot carry an outcome that
  differs between fuels — and the executable's cached instantiation
  (`sharedOpsC`, `ConLeche/Cached/CheckerC.lean`) delivers it.  The
  `Unit` result is what makes the combinator fuel-monotone: an attempt
  that fails at one fuel and succeeds at a larger one changes which
  branch ran, not whether the whole succeeded. -/
  orElse : m Bool → (Option CheckError → m Unit) → m Unit

variable (mode : CheckMode)

/-- The pure instantiation, at an arbitrary fuel. -/
def fueledOps (F : Nat) : CheckerOps CheckM where
  annotate env d e := annotateCore mode env F d e
  inferType env d e := inferTypeCore mode env F d e
  isDefEq env d a b := isDefEqCore mode env F d a b
  ensureSort env d e := ensureSortCore mode env F d e
  whnf env d e := ConLeche.whnf mode env F d e
  orElse x k := match x with
    | .ok true => pure ()
    | _ => k none

/-- The pure instantiation, at the standard fuel. -/
def pureOps : CheckerOps CheckM := fueledOps mode checkFuel

/-- **The verdict at a term whose constants do not all resolve.**

Every front door for stream-supplied data — a declaration's type, a
value, a recursor rule's right-hand side — guards it with
`Expr.constsResolve` (or its indexed / cached twin) and throws here on
a `false`.  A term that mentions `sorryAx` DECLINES: that axiom is
tolerated as a declaration and installs nothing, so a use of it is a
positively detected unsupported feature, never a malformed stream.
Anything else is an unknown constant, and rejects with the message
unchanged.  `where_` names the slot, e.g. `"type of Foo"`.

`Expr.mentionsConst` is the same walk `constsResolve` just ran (the
`.proj` struct name included) and is memoized by `@[csimp]`
(`ConLeche/Kernel/Inductives/StructParts.lean`), so a DAG-shared term
does not unfold here.  The companion `unknownConstError`
(`ConLeche/Kernel/Core.lean`) decides the same question inside
inference, which the annotation pass reaches before this guard runs. -/
def unresolvedConstsError (where_ : String) (e : Expr) : CheckError :=
  if e.mentionsConst sorryAxName then
    .notImplemented s!"use of the sorryAx axiom in {where_}"
  else .invalid s!"unknown constant in {where_}"

variable {m : Type → Type} [Monad m] [MonadExceptOf CheckError m]

/-- Checks common to all declarations: fresh name, well-formed universe
parameters, and a type that is a type and mentions only declared
parameters.  Returns the constant with its type **annotated**
(`annotate`); the guards run on the annotated type. -/
def checkConstantVal (ops : CheckerOps m) (env : Env) (cv : ConstantVal) : m ConstantVal := do
  if (env.find? cv.name).isSome then
    throw (.invalid s!"duplicate declaration {cv.name}")
  if reservedBasisNames.contains cv.name then
    throw (.invalid s!"reserved basis name {cv.name}")
  if cv.name.isProjFnShape then
    throw (.invalid s!"reserved projection name {cv.name}")
  unless Name.nodup cv.levelParams do
    throw (.invalid s!"duplicate universe parameters in {cv.name}")
  unless cv.type.looseBVarsBounded 0 do
    throw (.invalid s!"loose bound variable in type of {cv.name}")
  if cv.type.hasFvar then
    throw (.invalid s!"unexpected free variable in type of {cv.name}")
  let type ← ops.annotate env 0 cv.type
  unless type.allLevelParamsDefined cv.levelParams do
    throw (.invalid s!"undeclared universe parameter in type of {cv.name}")
  unless type.constsResolve env do
    throw (unresolvedConstsError s!"type of {cv.name}" type)
  let stype ← ops.inferType env 0 type
  let _u ← ops.ensureSort env 0 stype
  pure { cv with type := type }

/-- Open the first `n` `∀`-binders at fresh free variables `0..n-1`
(each fvar's type is the binder domain, instantiated with the earlier
fvars).  Returns the fvars and the opened body. -/
def openPisAtFvars : Nat → Expr → Nat → Option (List Expr × Expr)
  | 0, e, _ => some ([], e)
  | n + 1, .forallE dom body _, i =>
    let fv : Expr := .fvar i dom
    match openPisAtFvars n (body.instantiate1 fv) (i + 1) with
    | some (fvs, e) => some (fv :: fvs, e)
    | none => none
  | _ + 1, _, _ => none

/-- Core of `openPisAtFvarsF`: `acc` holds the already-created fvars,
innermost binder first.  Computes
`openPisAtFvars n (e.instantiateList acc) i` whenever `e` raw-strips
`n` `∀`-binders (`openPisAtFvarsFGo_sound`), `none` otherwise —
one `instantiateList` pass per domain instead of one whole-telescope
`instantiate1` pass per binder. -/
def openPisAtFvarsFGo (acc : List Expr) :
    Nat → Expr → Nat → Option (List Expr × Expr)
  | 0, e, _ => some ([], e.instantiateList acc)
  | n + 1, .forallE dom body _, i =>
    let fv : Expr := .fvar i (dom.instantiateList acc)
    match openPisAtFvarsFGo (fv :: acc) n body (i + 1) with
    | some (fvs, e) => some (fv :: fvs, e)
    | none => none
  | _ + 1, _, _ => none

/-- One-pass `openPisAtFvars` (equal to it: `openPisAtFvarsF_eq`; the
fallback covers telescopes whose binders only appear after
substitution). -/
def openPisAtFvarsF (n : Nat) (e : Expr) (i : Nat) :
    Option (List Expr × Expr) :=
  match openPisAtFvarsFGo [] n e i with
  | some r => some r
  | none => openPisAtFvars n e i

/-- Unwrap an optional value or fail with the given error (the
`Option`-shaped checks below stay bind-shaped for the verification
batteries). -/
def unwrapOr {α : Type} (o : Option α) (err : CheckError) : m α :=
  match o with
  | some a => pure a
  | none => throw err

/-- The stored constant under `n`, as a `ConstantVal`, if any.  The
iota-certificate checks below consume only the stored constant's
*type* (any stored constant witnesses its type's inhabitation in the
model — `EnvModel.mem_type` is kind-agnostic), so no theorem-kind
filter is imposed. -/
def Env.findCV? (env : Env) (n : Name) : Option ConstantVal :=
  (env.find? n).map (·.toConstantVal)

/-- The result sort of a syntactic pi telescope (the sort the type
former's type ends in), if it ends in a sort at all. -/
def piResultSort (e : Expr) : Option Level :=
  match e.piResult with
  | .sort u => some u
  | _ => none



end ConLeche
