import Setlec.Kernel.Basis.Names

/-!
# The pinned `Empty` basis block

Raw pin (matched against the preprocessor's emission) and its annotated
form (see `Setlec.Kernel.Basis`).
-/

namespace Setlec

open Name (anonymous)

/-- The pinned `Empty` basis block (no constructors, no iota rules). -/
def emptyBasis : List ConstantInfo := [
  .indInfo ⟨(anonymous |>.str "Empty"), [], (.sort (.succ .zero))⟩ {},
  .recInfo ⟨((anonymous |>.str "Empty") |>.str "rec"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "motive") (.forallE (anonymous |>.str "t") (.const (anonymous |>.str "Empty") []) (.sort (.param (anonymous |>.str "u"))) ⟨.default, none⟩) (.forallE (anonymous |>.str "t") (.const (anonymous |>.str "Empty") []) (.app (.bvar 1) (.bvar 0)) ⟨.default, none⟩) ⟨.default, none⟩)⟩ 0 1 0 0 []]

/-! ## The annotated declarations

Generated by running the checker's own `annotate` over the pinned block
in install order (`AnnotateBasis.lean`); the installation stores these
verbatim, and the model proofs work against them.  Do not edit by
hand. -/

/-- Annotated basis declaration (generated). -/
def emptyA : ConstantInfo :=
  Setlec.ConstantInfo.indInfo
    { name := Setlec.Name.str (Setlec.Name.anonymous) "Empty",
      levelParams := [],
      type := Setlec.Expr.sort (Setlec.Level.succ (Setlec.Level.zero)) }
    { eta := false, etaCtor := Setlec.Name.anonymous, etaParams := 0, etaFields := 0, unitlike := false, ruleK := false }

/-- Annotated basis declaration (generated). -/
def emptyRecA : ConstantInfo :=
  Setlec.ConstantInfo.recInfo
    { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Empty") "rec",
      levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
      type := Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "motive")
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "t")
                  (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Empty") [])
                  (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.succ (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))) })
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "t")
                  (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Empty") [])
                  (Setlec.Expr.app (Setlec.Expr.bvar 1) (Setlec.Expr.bvar 0))
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")) })
                { bi := Setlec.BinderInfo.default,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.succ (Setlec.Level.zero))
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))) } }
    0
    1
    0
    0
    []

end Setlec
