import Setlec.Kernel.Basis.Names

/-!
# The pinned `Nat` basis block

Raw pin (matched against the preprocessor's emission) and its annotated
form (see `Setlec.Kernel.Basis`).
-/

namespace Setlec

open Name (anonymous)

/-- The pinned `Nat` basis block. -/
def natBasis : List ConstantInfo := [
  .indInfo ⟨(anonymous |>.str "Nat"), [], (.sort (.succ .zero))⟩ {},
  .ctorInfo ⟨((anonymous |>.str "Nat") |>.str "zero"), [], (.const (anonymous |>.str "Nat") [])⟩ 0 0,
  .ctorInfo ⟨((anonymous |>.str "Nat") |>.str "succ"), [], (.forallE (anonymous |>.str "n") (.const (anonymous |>.str "Nat") []) (.const (anonymous |>.str "Nat") []) ⟨.default, .never⟩)⟩ 0 1,
  .recInfo ⟨((anonymous |>.str "Nat") |>.str "rec"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "motive") (.forallE (anonymous |>.str "t") (.const (anonymous |>.str "Nat") []) (.sort (.param (anonymous |>.str "u"))) ⟨.default, .never⟩) (.forallE (anonymous |>.str "zero") (.app (.bvar 0) (.const ((anonymous |>.str "Nat") |>.str "zero") [])) (.forallE (anonymous |>.str "succ") (.forallE (anonymous |>.str "n") (.const (anonymous |>.str "Nat") []) (.forallE (anonymous |>.str "n_ih") (.app (.bvar 2) (.bvar 0)) (.app (.bvar 3) (.app (.const ((anonymous |>.str "Nat") |>.str "succ") []) (.bvar 1))) ⟨.default, .never⟩) ⟨.default, .never⟩) (.forallE (anonymous |>.str "t") (.const (anonymous |>.str "Nat") []) (.app (.bvar 3) (.bvar 0)) ⟨.default, .never⟩) ⟨.default, .never⟩) ⟨.default, .never⟩) ⟨.implicit, .never⟩)⟩ 3 3
    [⟨((anonymous |>.str "Nat") |>.str "zero"), 0, 0, .inert, (.lam (anonymous |>.str "motive") (.forallE (anonymous |>.str "t") (.const (anonymous |>.str "Nat") []) (.sort (.param (anonymous |>.str "u"))) ⟨.default, .never⟩) (.lam (anonymous |>.str "zero") (.app (.bvar 0) (.const ((anonymous |>.str "Nat") |>.str "zero") [])) (.lam (anonymous |>.str "succ") (.forallE (anonymous |>.str "n") (.const (anonymous |>.str "Nat") []) (.forallE (anonymous |>.str "n_ih") (.app (.bvar 2) (.bvar 0)) (.app (.bvar 3) (.app (.const ((anonymous |>.str "Nat") |>.str "succ") []) (.bvar 1))) ⟨.default, .never⟩) ⟨.default, .never⟩) (.bvar 1) ⟨.default, .never⟩) ⟨.default, .never⟩) ⟨.default, .never⟩)⟩,
      ⟨((anonymous |>.str "Nat") |>.str "succ"), 1, 0, .inert, (.lam (anonymous |>.str "motive") (.forallE (anonymous |>.str "t") (.const (anonymous |>.str "Nat") []) (.sort (.param (anonymous |>.str "u"))) ⟨.default, .never⟩) (.lam (anonymous |>.str "zero") (.app (.bvar 0) (.const ((anonymous |>.str "Nat") |>.str "zero") [])) (.lam (anonymous |>.str "succ") (.forallE (anonymous |>.str "n") (.const (anonymous |>.str "Nat") []) (.forallE (anonymous |>.str "n_ih") (.app (.bvar 2) (.bvar 0)) (.app (.bvar 3) (.app (.const ((anonymous |>.str "Nat") |>.str "succ") []) (.bvar 1))) ⟨.default, .never⟩) ⟨.default, .never⟩) (.lam (anonymous |>.str "n") (.const (anonymous |>.str "Nat") []) (.app (.app (.bvar 1) (.bvar 0)) (.app (.app (.app (.app (.const ((anonymous |>.str "Nat") |>.str "rec") [(.param (anonymous |>.str "u"))]) (.bvar 3)) (.bvar 2)) (.bvar 1)) (.bvar 0))) ⟨.default, .never⟩) ⟨.default, .never⟩) ⟨.default, .never⟩) ⟨.default, .never⟩)⟩]]

/-! ## The annotated declarations

Generated by running the checker's own `annotate` over the pinned block
in install order (`AnnotateBasis.lean`); the installation stores these
verbatim, and the model proofs work against them.  Do not edit by
hand. -/

/-- Annotated basis declaration (generated). -/
def natA : ConstantInfo :=
  Setlec.ConstantInfo.indInfo
    { name := Setlec.Name.str (Setlec.Name.anonymous) "Nat",
      levelParams := [],
      type := Setlec.Expr.sort (Setlec.Level.succ (Setlec.Level.zero)) }
    { eta := false,
      etaCtor := Setlec.Name.anonymous,
      etaParams := 0,
      etaFields := 0,
      unitlike := false,
      unitParams := 0,
      ruleK := false }

/-- Annotated basis declaration (generated). -/
def natZeroA : ConstantInfo :=
  Setlec.ConstantInfo.ctorInfo
    { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nat") "zero",
      levelParams := [],
      type := Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [] }
    0
    0

/-- Annotated basis declaration (generated). -/
def natSuccA : ConstantInfo :=
  Setlec.ConstantInfo.ctorInfo
    { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nat") "succ",
      levelParams := [],
      type := Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "n")
                (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
                (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
                { bi := Setlec.BinderInfo.default, pw := Setlec.PropWhen.never } }
    0
    1

/-- Annotated basis declaration (generated). -/
def natRecA : ConstantInfo :=
  Setlec.ConstantInfo.recInfo
    { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nat") "rec",
      levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
      type := Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "motive")
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "t")
                  (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
                  (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
                  { bi := Setlec.BinderInfo.default, pw := Setlec.PropWhen.never })
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "zero")
                  (Setlec.Expr.app
                    (Setlec.Expr.bvar 0)
                    (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nat") "zero") []))
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "succ")
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "n")
                      (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
                      (Setlec.Expr.forallE
                        (Setlec.Name.str (Setlec.Name.anonymous) "n_ih")
                        (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 0))
                        (Setlec.Expr.app
                          (Setlec.Expr.bvar 3)
                          (Setlec.Expr.app
                            (Setlec.Expr.const
                              (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nat") "succ")
                              [])
                            (Setlec.Expr.bvar 1)))
                        { bi := Setlec.BinderInfo.default,
                          pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                      { bi := Setlec.BinderInfo.default,
                        pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "t")
                      (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
                      (Setlec.Expr.app (Setlec.Expr.bvar 3) (Setlec.Expr.bvar 0))
                      { bi := Setlec.BinderInfo.default,
                        pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                    { bi := Setlec.BinderInfo.default,
                      pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                  { bi := Setlec.BinderInfo.default,
                    pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                { bi := Setlec.BinderInfo.implicit,
                  pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] } }
    3
    3
    [{ ctor := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nat") "zero",
       nfields := 0,
       ctorParams := 0,
       fire := Setlec.RecRuleFire.plain,
       rhs := Setlec.Expr.lam
                (Setlec.Name.str (Setlec.Name.anonymous) "motive")
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "t")
                  (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
                  (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
                  { bi := Setlec.BinderInfo.default, pw := Setlec.PropWhen.never })
                (Setlec.Expr.lam
                  (Setlec.Name.str (Setlec.Name.anonymous) "zero")
                  (Setlec.Expr.app
                    (Setlec.Expr.bvar 0)
                    (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nat") "zero") []))
                  (Setlec.Expr.lam
                    (Setlec.Name.str (Setlec.Name.anonymous) "succ")
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "n")
                      (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
                      (Setlec.Expr.forallE
                        (Setlec.Name.str (Setlec.Name.anonymous) "n_ih")
                        (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 0))
                        (Setlec.Expr.app
                          (Setlec.Expr.bvar 3)
                          (Setlec.Expr.app
                            (Setlec.Expr.const
                              (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nat") "succ")
                              [])
                            (Setlec.Expr.bvar 1)))
                        { bi := Setlec.BinderInfo.default,
                          pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                      { bi := Setlec.BinderInfo.default,
                        pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                    (Setlec.Expr.bvar 1)
                    { bi := Setlec.BinderInfo.default,
                      pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                  { bi := Setlec.BinderInfo.default,
                    pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                { bi := Setlec.BinderInfo.default,
                  pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] } },
     { ctor := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nat") "succ",
       nfields := 1,
       ctorParams := 0,
       fire := Setlec.RecRuleFire.plain,
       rhs := Setlec.Expr.lam
                (Setlec.Name.str (Setlec.Name.anonymous) "motive")
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "t")
                  (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
                  (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
                  { bi := Setlec.BinderInfo.default, pw := Setlec.PropWhen.never })
                (Setlec.Expr.lam
                  (Setlec.Name.str (Setlec.Name.anonymous) "zero")
                  (Setlec.Expr.app
                    (Setlec.Expr.bvar 0)
                    (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nat") "zero") []))
                  (Setlec.Expr.lam
                    (Setlec.Name.str (Setlec.Name.anonymous) "succ")
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "n")
                      (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
                      (Setlec.Expr.forallE
                        (Setlec.Name.str (Setlec.Name.anonymous) "n_ih")
                        (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 0))
                        (Setlec.Expr.app
                          (Setlec.Expr.bvar 3)
                          (Setlec.Expr.app
                            (Setlec.Expr.const
                              (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nat") "succ")
                              [])
                            (Setlec.Expr.bvar 1)))
                        { bi := Setlec.BinderInfo.default,
                          pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                      { bi := Setlec.BinderInfo.default,
                        pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                    (Setlec.Expr.lam
                      (Setlec.Name.str (Setlec.Name.anonymous) "n")
                      (Setlec.Expr.const (Setlec.Name.str (Setlec.Name.anonymous) "Nat") [])
                      (Setlec.Expr.app
                        (Setlec.Expr.app (Setlec.Expr.bvar 1) (Setlec.Expr.bvar 0))
                        (Setlec.Expr.app
                          (Setlec.Expr.app
                            (Setlec.Expr.app
                              (Setlec.Expr.app
                                (Setlec.Expr.const
                                  (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Nat") "rec")
                                  [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                                (Setlec.Expr.bvar 3))
                              (Setlec.Expr.bvar 2))
                            (Setlec.Expr.bvar 1))
                          (Setlec.Expr.bvar 0)))
                      { bi := Setlec.BinderInfo.default,
                        pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                    { bi := Setlec.BinderInfo.default,
                      pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                  { bi := Setlec.BinderInfo.default,
                    pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] })
                { bi := Setlec.BinderInfo.default,
                  pw := Setlec.PropWhen.ifAllZero [Setlec.Name.str (Setlec.Name.anonymous) "u"] } }]

end Setlec
