import Setlec.Kernel.Basis.Names

/-!
# The pinned `PSigma'` basis block

Raw pin (matched against the preprocessor's emission) and its annotated
form (see `Setlec.Kernel.Basis`).
-/

namespace Setlec

open Name (anonymous)

/-- The pinned `PSigma'` basis block. -/
def psigmaBasis : List ConstantInfo := [
  .indInfo ⟨(anonymous |>.str "PSigma'"), [(anonymous |>.str "u"), (anonymous |>.str "v")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous |>.str "β") (.forallE (anonymous |>.str "x") (.bvar 0) (.sort (.param (anonymous |>.str "v"))) ⟨.default⟩) (.sort (.max (.param (anonymous |>.str "u")) (.param (anonymous |>.str "v")))) ⟨.default⟩) ⟨.implicit⟩)⟩ ⟨true, psigmaMkName, 2, 2, false, 0, false⟩,
  .ctorInfo ⟨((anonymous |>.str "PSigma'") |>.str "mk"), [(anonymous |>.str "u"), (anonymous |>.str "v")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous |>.str "β") (.forallE (anonymous |>.str "x") (.bvar 0) (.sort (.param (anonymous |>.str "v"))) ⟨.default⟩) (.forallE (anonymous |>.str "fst") (.bvar 1) (.forallE (anonymous |>.str "snd") (.app (.bvar 1) (.bvar 0)) (.app (.app (.const (anonymous |>.str "PSigma'") [(.param (anonymous |>.str "u")), (.param (anonymous |>.str "v"))]) (.bvar 3)) (.bvar 2)) ⟨.default⟩) ⟨.default⟩) ⟨.implicit⟩) ⟨.implicit⟩)⟩ 2 2,
  .recInfo ⟨((anonymous |>.str "PSigma'") |>.str "rec"), [(anonymous |>.str "u"), (anonymous |>.str "v")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous |>.str "β") (.forallE (anonymous |>.str "x") (.bvar 0) (.sort (.param (anonymous |>.str "v"))) ⟨.default⟩) (.forallE (anonymous |>.str "motive") (.forallE (anonymous |>.str "t") (.app (.app (.const (anonymous |>.str "PSigma'") [(.param (anonymous |>.str "u")), (.param (anonymous |>.str "v"))]) (.bvar 1)) (.bvar 0)) (.sort .zero) ⟨.default⟩) (.forallE (anonymous |>.str "mk") (.forallE (anonymous |>.str "fst") (.bvar 2) (.forallE (anonymous |>.str "snd") (.app (.bvar 2) (.bvar 0)) (.app (.bvar 2) (.app (.app (.app (.app (.const ((anonymous |>.str "PSigma'") |>.str "mk") [(.param (anonymous |>.str "u")), (.param (anonymous |>.str "v"))]) (.bvar 4)) (.bvar 3)) (.bvar 1)) (.bvar 0))) ⟨.default⟩) ⟨.default⟩) (.forallE (anonymous |>.str "t") (.app (.app (.const (anonymous |>.str "PSigma'") [(.param (anonymous |>.str "u")), (.param (anonymous |>.str "v"))]) (.bvar 3)) (.bvar 2)) (.app (.bvar 2) (.bvar 0)) ⟨.default⟩) ⟨.default⟩) ⟨.implicit⟩) ⟨.implicit⟩) ⟨.implicit⟩)⟩ 4 4
    [⟨((anonymous |>.str "PSigma'") |>.str "mk"), 2, 0, .inert, (.lam (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.lam (anonymous |>.str "β") (.forallE (anonymous |>.str "x") (.bvar 0) (.sort (.param (anonymous |>.str "v"))) ⟨.default⟩) (.lam (anonymous |>.str "motive") (.forallE (anonymous |>.str "t") (.app (.app (.const (anonymous |>.str "PSigma'") [(.param (anonymous |>.str "u")), (.param (anonymous |>.str "v"))]) (.bvar 1)) (.bvar 0)) (.sort .zero) ⟨.default⟩) (.lam (anonymous |>.str "mk") (.forallE (anonymous |>.str "fst") (.bvar 2) (.forallE (anonymous |>.str "snd") (.app (.bvar 2) (.bvar 0)) (.app (.bvar 2) (.app (.app (.app (.app (.const ((anonymous |>.str "PSigma'") |>.str "mk") [(.param (anonymous |>.str "u")), (.param (anonymous |>.str "v"))]) (.bvar 4)) (.bvar 3)) (.bvar 1)) (.bvar 0))) ⟨.default⟩) ⟨.default⟩) (.lam (anonymous |>.str "fst") (.bvar 3) (.lam (anonymous |>.str "snd") (.app (.bvar 3) (.bvar 0)) (.app (.app (.bvar 2) (.bvar 1)) (.bvar 0)) ⟨.default⟩) ⟨.default⟩) ⟨.default⟩) ⟨.default⟩) ⟨.default⟩) ⟨.implicit⟩)⟩]]

/-! ## The annotated declarations

Generated by running the checker's own `annotate` over the pinned block
in install order (`AnnotateBasis.lean`); the installation stores these
verbatim, and the model proofs work against them.  Do not edit by
hand. -/

/-- Annotated basis declaration (generated). -/
def psigmaA : ConstantInfo :=
  Setlec.ConstantInfo.indInfo
    { name := Setlec.Name.str (Setlec.Name.anonymous) "PSigma'",
      levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u", Setlec.Name.str (Setlec.Name.anonymous) "v"],
      type := Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "α")
                (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "β")
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "x")
                    (Setlec.Expr.bvar 0)
                    (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                    { bi := Setlec.BinderInfo.default})
                  (Setlec.Expr.sort
                    (Setlec.Level.max
                      (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                      (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v"))))
                  { bi := Setlec.BinderInfo.default})
                { bi := Setlec.BinderInfo.implicit} }
    { eta := true,
      etaCtor := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "PSigma'") "mk",
      etaParams := 2,
      etaFields := 2,
      unitlike := false,
      ruleK := false }

/-- Annotated basis declaration (generated). -/
def psigmaMkA : ConstantInfo :=
  Setlec.ConstantInfo.ctorInfo
    { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "PSigma'") "mk",
      levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u", Setlec.Name.str (Setlec.Name.anonymous) "v"],
      type := Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "α")
                (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "β")
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "x")
                    (Setlec.Expr.bvar 0)
                    (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                    { bi := Setlec.BinderInfo.default})
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "fst")
                    (Setlec.Expr.bvar 1)
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "snd")
                      (Setlec.Expr.app (Setlec.Expr.bvar 1) (Setlec.Expr.bvar 0))
                      (Setlec.Expr.app
                        (Setlec.Expr.app
                          (Setlec.Expr.const
                            (Setlec.Name.str (Setlec.Name.anonymous) "PSigma'")
                            [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"),
                             Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")])
                          (Setlec.Expr.bvar 3))
                        (Setlec.Expr.bvar 2))
                      { bi := Setlec.BinderInfo.default})
                    { bi := Setlec.BinderInfo.default})
                  { bi := Setlec.BinderInfo.implicit})
                { bi := Setlec.BinderInfo.implicit} }
    2
    2

/-- Annotated basis declaration (generated). -/
def psigmaRecA : ConstantInfo :=
  Setlec.ConstantInfo.recInfo
    { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "PSigma'") "rec",
      levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u", Setlec.Name.str (Setlec.Name.anonymous) "v"],
      type := Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "α")
                (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "β")
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "x")
                    (Setlec.Expr.bvar 0)
                    (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                    { bi := Setlec.BinderInfo.default})
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "motive")
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "t")
                      (Setlec.Expr.app
                        (Setlec.Expr.app
                          (Setlec.Expr.const
                            (Setlec.Name.str (Setlec.Name.anonymous) "PSigma'")
                            [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"),
                             Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")])
                          (Setlec.Expr.bvar 1))
                        (Setlec.Expr.bvar 0))
                      (Setlec.Expr.sort (Setlec.Level.zero))
                      { bi := Setlec.BinderInfo.default})
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "mk")
                      (Setlec.Expr.forallE
                        (Setlec.Name.str (Setlec.Name.anonymous) "fst")
                        (Setlec.Expr.bvar 2)
                        (Setlec.Expr.forallE
                          (Setlec.Name.str (Setlec.Name.anonymous) "snd")
                          (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 0))
                          (Setlec.Expr.app
                            (Setlec.Expr.bvar 2)
                            (Setlec.Expr.app
                              (Setlec.Expr.app
                                (Setlec.Expr.app
                                  (Setlec.Expr.app
                                    (Setlec.Expr.const
                                      (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "PSigma'") "mk")
                                      [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"),
                                       Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")])
                                    (Setlec.Expr.bvar 4))
                                  (Setlec.Expr.bvar 3))
                                (Setlec.Expr.bvar 1))
                              (Setlec.Expr.bvar 0)))
                          { bi := Setlec.BinderInfo.default})
                        { bi := Setlec.BinderInfo.default})
                      (Setlec.Expr.forallE
                        (Setlec.Name.str (Setlec.Name.anonymous) "t")
                        (Setlec.Expr.app
                          (Setlec.Expr.app
                            (Setlec.Expr.const
                              (Setlec.Name.str (Setlec.Name.anonymous) "PSigma'")
                              [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"),
                               Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")])
                            (Setlec.Expr.bvar 3))
                          (Setlec.Expr.bvar 2))
                        (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 0))
                        { bi := Setlec.BinderInfo.default})
                      { bi := Setlec.BinderInfo.default})
                    { bi := Setlec.BinderInfo.implicit})
                  { bi := Setlec.BinderInfo.implicit})
                { bi := Setlec.BinderInfo.implicit} }
    4
    4
    [{ ctor := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "PSigma'") "mk",
       nfields := 2,
       ctorParams := 2,
       fire := .plain,
       rhs := Setlec.Expr.lam
                (Setlec.Name.str (Setlec.Name.anonymous) "α")
                (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
                (Setlec.Expr.lam
                  (Setlec.Name.str (Setlec.Name.anonymous) "β")
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "x")
                    (Setlec.Expr.bvar 0)
                    (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                    { bi := Setlec.BinderInfo.default})
                  (Setlec.Expr.lam
                    (Setlec.Name.str (Setlec.Name.anonymous) "motive")
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "t")
                      (Setlec.Expr.app
                        (Setlec.Expr.app
                          (Setlec.Expr.const
                            (Setlec.Name.str (Setlec.Name.anonymous) "PSigma'")
                            [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"),
                             Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")])
                          (Setlec.Expr.bvar 1))
                        (Setlec.Expr.bvar 0))
                      (Setlec.Expr.sort (Setlec.Level.zero))
                      { bi := Setlec.BinderInfo.default})
                    (Setlec.Expr.lam
                      (Setlec.Name.str (Setlec.Name.anonymous) "mk")
                      (Setlec.Expr.forallE
                        (Setlec.Name.str (Setlec.Name.anonymous) "fst")
                        (Setlec.Expr.bvar 2)
                        (Setlec.Expr.forallE
                          (Setlec.Name.str (Setlec.Name.anonymous) "snd")
                          (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 0))
                          (Setlec.Expr.app
                            (Setlec.Expr.bvar 2)
                            (Setlec.Expr.app
                              (Setlec.Expr.app
                                (Setlec.Expr.app
                                  (Setlec.Expr.app
                                    (Setlec.Expr.const
                                      (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "PSigma'") "mk")
                                      [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"),
                                       Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")])
                                    (Setlec.Expr.bvar 4))
                                  (Setlec.Expr.bvar 3))
                                (Setlec.Expr.bvar 1))
                              (Setlec.Expr.bvar 0)))
                          { bi := Setlec.BinderInfo.default})
                        { bi := Setlec.BinderInfo.default})
                      (Setlec.Expr.lam
                        (Setlec.Name.str (Setlec.Name.anonymous) "fst")
                        (Setlec.Expr.bvar 3)
                        (Setlec.Expr.lam
                          (Setlec.Name.str (Setlec.Name.anonymous) "snd")
                          (Setlec.Expr.app (Setlec.Expr.bvar 3) (Setlec.Expr.bvar 0))
                          (Setlec.Expr.app
                            (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 1))
                            (Setlec.Expr.bvar 0))
                          { bi := Setlec.BinderInfo.default})
                        { bi := Setlec.BinderInfo.default})
                      { bi := Setlec.BinderInfo.default})
                    { bi := Setlec.BinderInfo.default})
                  { bi := Setlec.BinderInfo.default})
                { bi := Setlec.BinderInfo.implicit} }]


/-! ## The pinned pair projection-table entries

The two `native` projection-table entries for the basis pair,
installed with the block: `.proj` nodes on `PSigma'` are typed by
these level-parametric types and reduced by the generic structural
rule.  The types are the checker's own `annotate` output over the
pinned block (generated; do not edit by hand). -/

/-- Annotated projection type of the pair's first component
(generated). -/
def pairFstTyA : Expr :=
  Setlec.Expr.forallE
    (Setlec.Name.str (Setlec.Name.anonymous) "α")
    (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
    (Setlec.Expr.forallE
      (Setlec.Name.str (Setlec.Name.anonymous) "β")
      (Setlec.Expr.forallE
        (Setlec.Name.str (Setlec.Name.anonymous) "x")
        (Setlec.Expr.bvar 0)
        (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
        { bi := Setlec.BinderInfo.default})
      (Setlec.Expr.forallE
        (Setlec.Name.str (Setlec.Name.anonymous) "t")
        (Setlec.Expr.app
          (Setlec.Expr.app
            (Setlec.Expr.const
              (Setlec.Name.str (Setlec.Name.anonymous) "PSigma'")
              [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"),
               Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")])
            (Setlec.Expr.bvar 1))
          (Setlec.Expr.bvar 0))
        (Setlec.Expr.bvar 2)
        { bi := Setlec.BinderInfo.default})
      { bi := Setlec.BinderInfo.implicit})
    { bi := Setlec.BinderInfo.implicit}

/-- Annotated projection type of the pair's second component
(generated). -/
def pairSndTyA : Expr :=
  Setlec.Expr.forallE
    (Setlec.Name.str (Setlec.Name.anonymous) "α")
    (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
    (Setlec.Expr.forallE
      (Setlec.Name.str (Setlec.Name.anonymous) "β")
      (Setlec.Expr.forallE
        (Setlec.Name.str (Setlec.Name.anonymous) "x")
        (Setlec.Expr.bvar 0)
        (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
        { bi := Setlec.BinderInfo.default})
      (Setlec.Expr.forallE
        (Setlec.Name.str (Setlec.Name.anonymous) "t")
        (Setlec.Expr.app
          (Setlec.Expr.app
            (Setlec.Expr.const
              (Setlec.Name.str (Setlec.Name.anonymous) "PSigma'")
              [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"),
               Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")])
            (Setlec.Expr.bvar 1))
          (Setlec.Expr.bvar 0))
        (Setlec.Expr.app
          (Setlec.Expr.bvar 1)
          (Setlec.Expr.proj (Setlec.Name.str (Setlec.Name.anonymous) "PSigma'") 0 (Setlec.Expr.bvar 0)))
        { bi := Setlec.BinderInfo.default})
      { bi := Setlec.BinderInfo.implicit})
    { bi := Setlec.BinderInfo.implicit}

/-- The pinned first-projection entry of the basis pair. -/
def pairFstEntry : ProjEntry :=
  ⟨psigmaName, 0, [anonymous |>.str "u", anonymous |>.str "v"],
    2, psigmaMkName, 2, pairFstTyA,
    .param (anonymous |>.str "u"),
    .max (.param (anonymous |>.str "u")) (.param (anonymous |>.str "v")),
    true, false⟩

/-- The pinned second-projection entry of the basis pair. -/
def pairSndEntry : ProjEntry :=
  ⟨psigmaName, 1, [anonymous |>.str "u", anonymous |>.str "v"],
    2, psigmaMkName, 2, pairSndTyA,
    .param (anonymous |>.str "v"),
    .max (.param (anonymous |>.str "u")) (.param (anonymous |>.str "v")),
    true, false⟩

/-- The pinned pair projection-table constants. -/
def pairFstA : ConstantInfo := .projInfo pairFstEntry

def pairSndA : ConstantInfo := .projInfo pairSndEntry

end Setlec
