import Setlec.Kernel.Basis.Names

/-!
# The pinned `PUnit` basis block

Raw pin (matched against the preprocessor's emission) and its annotated
form (see `Setlec.Kernel.Basis`).
-/

namespace Setlec

open Name (anonymous)

/-- The pinned `PUnit` basis block. -/
def punitBasis : List ConstantInfo := [
  .indInfo ⟨(anonymous |>.str "PUnit"), [(anonymous |>.str "u")], (.sort (.param (anonymous |>.str "u")))⟩ { unitlike := true },
  .ctorInfo ⟨((anonymous |>.str "PUnit") |>.str "unit"), [(anonymous |>.str "u")], (.const (anonymous |>.str "PUnit") [(.param (anonymous |>.str "u"))])⟩ 0 0,
  .recInfo ⟨((anonymous |>.str "PUnit") |>.str "rec"), [(anonymous |>.str "u_1"), (anonymous |>.str "u")], (.forallE (anonymous |>.str "motive") (.forallE (anonymous |>.str "t") (.const (anonymous |>.str "PUnit") [(.param (anonymous |>.str "u"))]) (.sort (.param (anonymous |>.str "u_1"))) ⟨.default, none⟩) (.forallE (anonymous |>.str "unit") (.app (.bvar 0) (.const ((anonymous |>.str "PUnit") |>.str "unit") [(.param (anonymous |>.str "u"))])) (.forallE (anonymous |>.str "t") (.const (anonymous |>.str "PUnit") [(.param (anonymous |>.str "u"))]) (.app (.bvar 2) (.bvar 0)) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.implicit, none⟩)⟩ 2 2
    [⟨((anonymous |>.str "PUnit") |>.str "unit"), 0, 0, .inert, (.lam (anonymous |>.str "motive") (.forallE (anonymous |>.str "t") (.const (anonymous |>.str "PUnit") [(.param (anonymous |>.str "u"))]) (.sort (.param (anonymous |>.str "u_1"))) ⟨.default, none⟩) (.lam (anonymous |>.str "unit") (.app (.bvar 0) (.const ((anonymous |>.str "PUnit") |>.str "unit") [(.param (anonymous |>.str "u"))])) (.bvar 0) ⟨.default, none⟩) ⟨.default, none⟩)⟩]]

/-! ## The annotated declarations

Generated by running the checker's own `annotate` over the pinned block
in install order (`AnnotateBasis.lean`); the installation stores these
verbatim, and the model proofs work against them.  Do not edit by
hand. -/

/-- Annotated basis declaration (generated). -/
def punitA : ConstantInfo :=
  Setlec.ConstantInfo.indInfo
    { name := Setlec.Name.str (Setlec.Name.anonymous) "PUnit",
      levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
      type := Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")) }
    { eta := false, etaCtor := Setlec.Name.anonymous, etaParams := 0, etaFields := 0, unitlike := true, ruleK := false }

/-- Annotated basis declaration (generated). -/
def punitUnitA : ConstantInfo :=
  Setlec.ConstantInfo.ctorInfo
    { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "PUnit") "unit",
      levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
      type := Setlec.Expr.const
                (Setlec.Name.str (Setlec.Name.anonymous) "PUnit")
                [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")] }
    0
    0

/-- Annotated basis declaration (generated). -/
def punitRecA : ConstantInfo :=
  Setlec.ConstantInfo.recInfo
    { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "PUnit") "rec",
      levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u_1", Setlec.Name.str (Setlec.Name.anonymous) "u"],
      type := Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "motive")
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "t")
                  (Setlec.Expr.const
                    (Setlec.Name.str (Setlec.Name.anonymous) "PUnit")
                    [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                  (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u_1")))
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.succ
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u_1"))) })
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "unit")
                  (Setlec.Expr.app
                    (Setlec.Expr.bvar 0)
                    (Setlec.Expr.const
                      (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "PUnit") "unit")
                      [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")]))
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "t")
                    (Setlec.Expr.const
                      (Setlec.Name.str (Setlec.Name.anonymous) "PUnit")
                      [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                    (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 0))
                    { bi := Setlec.BinderInfo.default,
                      cod := some (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u_1")) })
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u_1"))) })
                { bi := Setlec.BinderInfo.implicit,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u_1"))
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u_1")))) } }
    2
    2
    [{ ctor := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "PUnit") "unit",
       nfields := 0,
       ctorParams := 0,
       fire := .plain,
       rhs := Setlec.Expr.lam
                (Setlec.Name.str (Setlec.Name.anonymous) "motive")
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "t")
                  (Setlec.Expr.const
                    (Setlec.Name.str (Setlec.Name.anonymous) "PUnit")
                    [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                  (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u_1")))
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.succ
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u_1"))) })
                (Setlec.Expr.lam
                  (Setlec.Name.str (Setlec.Name.anonymous) "unit")
                  (Setlec.Expr.app
                    (Setlec.Expr.bvar 0)
                    (Setlec.Expr.const
                      (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "PUnit") "unit")
                      [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")]))
                  (Setlec.Expr.bvar 0)
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u_1")) })
                { bi := Setlec.BinderInfo.default,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u_1"))
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u_1"))) } }]

end Setlec
