import Setlec.Kernel.Basis.Names

/-!
# The pinned `Quot` basis block

Lean's kernel quotient bundle, pinned as an installed basis block:
`Quot` as a stored inductive with the single constructor `Quot.mk`,
the eliminators `Quot.lift`/`Quot.ind` as stored recursors with one
synthetic rule each (applying the lift/ind slot to the packed
element), and `Quot.sound` as a stored axiom (true in the set model).
Raw pins match the exporter's `quot` records (and `Quot.sound`'s
`axiom` record) verbatim; the annotated forms are generated by
`AnnotateBasis.lean` — do not edit them by hand.
-/

namespace Setlec

open Name (anonymous)

/-- The pinned `Quot` basis block. -/
def quotBasis : List ConstantInfo := [
  .indInfo ⟨(anonymous |>.str "Quot"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous |>.str "r") (.forallE (anonymous) (.bvar 0) (.forallE (anonymous) (.bvar 1) (.sort (.zero)) ⟨.default, none⟩) ⟨.default, none⟩) (.sort (.param (anonymous |>.str "u"))) ⟨.default, none⟩) ⟨.implicit, none⟩)⟩ {},
  .ctorInfo ⟨((anonymous |>.str "Quot") |>.str "mk"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous |>.str "r") (.forallE (anonymous) (.bvar 0) (.forallE (anonymous) (.bvar 1) (.sort (.zero)) ⟨.default, none⟩) ⟨.default, none⟩) (.forallE (anonymous |>.str "a") (.bvar 1) (.app (.app (.const (anonymous |>.str "Quot") [(.param (anonymous |>.str "u"))]) (.bvar 2)) (.bvar 1)) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.implicit, none⟩)⟩ 2 1,
  .recInfo ⟨((anonymous |>.str "Quot") |>.str "lift"), [(anonymous |>.str "u"), (anonymous |>.str "v")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous |>.str "r") (.forallE (anonymous) (.bvar 0) (.forallE (anonymous) (.bvar 1) (.sort (.zero)) ⟨.default, none⟩) ⟨.default, none⟩) (.forallE (anonymous |>.str "β") (.sort (.param (anonymous |>.str "v"))) (.forallE (anonymous |>.str "f") (.forallE (anonymous |>.str "a") (.bvar 2) (.bvar 1) ⟨.default, none⟩) (.forallE (anonymous |>.str "a") (.forallE (anonymous |>.str "a") (.bvar 3) (.forallE (anonymous |>.str "b") (.bvar 4) (.forallE (anonymous |>.str "a") (.app (.app (.bvar 4) (.bvar 1)) (.bvar 0)) (.app (.app (.app (.const (anonymous |>.str "Eq") [(.param (anonymous |>.str "v"))]) (.bvar 4)) (.app (.bvar 3) (.bvar 2))) (.app (.bvar 3) (.bvar 1))) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.default, none⟩) (.forallE (anonymous |>.str "a") (.app (.app (.const (anonymous |>.str "Quot") [(.param (anonymous |>.str "u"))]) (.bvar 4)) (.bvar 3)) (.bvar 3) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.implicit, none⟩) ⟨.implicit, none⟩) ⟨.implicit, none⟩)⟩ 3 1 1 0
    [⟨((anonymous |>.str "Quot") |>.str "mk"), 1, (.lam (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.lam (anonymous |>.str "r") (.forallE (anonymous) (.bvar 0) (.forallE (anonymous) (.bvar 1) (.sort (.zero)) ⟨.default, none⟩) ⟨.default, none⟩) (.lam (anonymous |>.str "β") (.sort (.param (anonymous |>.str "v"))) (.lam (anonymous |>.str "f") (.forallE (anonymous |>.str "a") (.bvar 2) (.bvar 1) ⟨.default, none⟩) (.lam (anonymous |>.str "h") (.forallE (anonymous |>.str "a") (.bvar 3) (.forallE (anonymous |>.str "b") (.bvar 4) (.forallE (anonymous |>.str "a") (.app (.app (.bvar 4) (.bvar 1)) (.bvar 0)) (.app (.app (.app (.const (anonymous |>.str "Eq") [(.param (anonymous |>.str "v"))]) (.bvar 4)) (.app (.bvar 3) (.bvar 2))) (.app (.bvar 3) (.bvar 1))) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.default, none⟩) (.lam (anonymous |>.str "a") (.bvar 4) (.app (.bvar 2) (.bvar 0)) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.default, none⟩)⟩],
  .recInfo ⟨((anonymous |>.str "Quot") |>.str "ind"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous |>.str "r") (.forallE (anonymous) (.bvar 0) (.forallE (anonymous) (.bvar 1) (.sort (.zero)) ⟨.default, none⟩) ⟨.default, none⟩) (.forallE (anonymous |>.str "β") (.forallE (anonymous |>.str "a") (.app (.app (.const (anonymous |>.str "Quot") [(.param (anonymous |>.str "u"))]) (.bvar 1)) (.bvar 0)) (.sort (.zero)) ⟨.default, none⟩) (.forallE (anonymous |>.str "mk") (.forallE (anonymous |>.str "a") (.bvar 2) (.app (.bvar 1) (.app (.app (.app (.const ((anonymous |>.str "Quot") |>.str "mk") [(.param (anonymous |>.str "u"))]) (.bvar 3)) (.bvar 2)) (.bvar 0))) ⟨.default, none⟩) (.forallE (anonymous |>.str "q") (.app (.app (.const (anonymous |>.str "Quot") [(.param (anonymous |>.str "u"))]) (.bvar 3)) (.bvar 2)) (.app (.bvar 2) (.bvar 0)) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.implicit, none⟩) ⟨.implicit, none⟩) ⟨.implicit, none⟩)⟩ 3 1 0 0
    [⟨((anonymous |>.str "Quot") |>.str "mk"), 1, (.lam (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.lam (anonymous |>.str "r") (.forallE (anonymous) (.bvar 0) (.forallE (anonymous) (.bvar 1) (.sort (.zero)) ⟨.default, none⟩) ⟨.default, none⟩) (.lam (anonymous |>.str "β") (.forallE (anonymous |>.str "a") (.app (.app (.const (anonymous |>.str "Quot") [(.param (anonymous |>.str "u"))]) (.bvar 1)) (.bvar 0)) (.sort (.zero)) ⟨.default, none⟩) (.lam (anonymous |>.str "mk") (.forallE (anonymous |>.str "a") (.bvar 2) (.app (.bvar 1) (.app (.app (.app (.const ((anonymous |>.str "Quot") |>.str "mk") [(.param (anonymous |>.str "u"))]) (.bvar 3)) (.bvar 2)) (.bvar 0))) ⟨.default, none⟩) (.lam (anonymous |>.str "a") (.bvar 3) (.app (.bvar 1) (.bvar 0)) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.default, none⟩) ⟨.default, none⟩)⟩],
  .axiomInfo ⟨((anonymous |>.str "Quot") |>.str "sound"), [(anonymous |>.str "u")], (.forallE (anonymous |>.str "α") (.sort (.param (anonymous |>.str "u"))) (.forallE (anonymous |>.str "r") (.forallE (anonymous) (.bvar 0) (.forallE (anonymous) (.bvar 1) (.sort (.zero)) ⟨.default, none⟩) ⟨.default, none⟩) (.forallE (anonymous |>.str "a") (.bvar 1) (.forallE (anonymous |>.str "b") (.bvar 2) (.forallE (anonymous) (.app (.app (.bvar 2) (.bvar 1)) (.bvar 0)) (.app (.app (.app (.const (anonymous |>.str "Eq") [(.param (anonymous |>.str "u"))]) (.app (.app (.const (anonymous |>.str "Quot") [(.param (anonymous |>.str "u"))]) (.bvar 4)) (.bvar 3))) (.app (.app (.app (.const ((anonymous |>.str "Quot") |>.str "mk") [(.param (anonymous |>.str "u"))]) (.bvar 4)) (.bvar 3)) (.bvar 2))) (.app (.app (.app (.const ((anonymous |>.str "Quot") |>.str "mk") [(.param (anonymous |>.str "u"))]) (.bvar 4)) (.bvar 3)) (.bvar 1))) ⟨.default, none⟩) ⟨.implicit, none⟩) ⟨.implicit, none⟩) ⟨.implicit, none⟩) ⟨.implicit, none⟩)⟩]

/-! ## The annotated declarations

Generated by running the checker's own `annotate` over the pinned block
in install order (`AnnotateBasis.lean`); the installation stores these
verbatim, and the model proofs work against them.  Do not edit by
hand. -/

/-- Annotated basis declaration (generated). -/
def quotA : ConstantInfo :=
  Setlec.ConstantInfo.indInfo
  { name := Setlec.Name.str (Setlec.Name.anonymous) "Quot",
    levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "α")
              (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "r")
                (Setlec.Expr.forallE
                  (Setlec.Name.anonymous)
                  (Setlec.Expr.bvar 0)
                  (Setlec.Expr.forallE
                    (Setlec.Name.anonymous)
                    (Setlec.Expr.bvar 1)
                    (Setlec.Expr.sort (Setlec.Level.zero))
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.succ (Setlec.Level.zero)) })
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))) })
                (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
                { bi := Setlec.BinderInfo.default,
                  cod := some (Setlec.Level.succ (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))) })
              { bi := Setlec.BinderInfo.implicit,
                cod := some (Setlec.Level.imax
                         (Setlec.Level.imax
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))))
                         (Setlec.Level.succ (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))) } }
  { eta := false,
    etaCtor := Setlec.Name.anonymous,
    etaParams := 0,
    etaFields := 0,
    unitlike := false,
    unitParams := 0,
    ruleK := false }

/-- Annotated basis declaration (generated). -/
def quotMkA : ConstantInfo :=
  Setlec.ConstantInfo.ctorInfo
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Quot") "mk",
    levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "α")
              (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "r")
                (Setlec.Expr.forallE
                  (Setlec.Name.anonymous)
                  (Setlec.Expr.bvar 0)
                  (Setlec.Expr.forallE
                    (Setlec.Name.anonymous)
                    (Setlec.Expr.bvar 1)
                    (Setlec.Expr.sort (Setlec.Level.zero))
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.succ (Setlec.Level.zero)) })
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))) })
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "a")
                  (Setlec.Expr.bvar 1)
                  (Setlec.Expr.app
                    (Setlec.Expr.app
                      (Setlec.Expr.const
                        (Setlec.Name.str (Setlec.Name.anonymous) "Quot")
                        [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                      (Setlec.Expr.bvar 2))
                    (Setlec.Expr.bvar 1))
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")) })
                { bi := Setlec.BinderInfo.default,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))) })
              { bi := Setlec.BinderInfo.implicit,
                cod := some (Setlec.Level.imax
                         (Setlec.Level.imax
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))))
                         (Setlec.Level.imax
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))) } }
  2
  1

/-- Annotated basis declaration (generated). -/
def quotLiftA : ConstantInfo :=
  Setlec.ConstantInfo.recInfo
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Quot") "lift",
    levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u", Setlec.Name.str (Setlec.Name.anonymous) "v"],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "α")
              (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "r")
                (Setlec.Expr.forallE
                  (Setlec.Name.anonymous)
                  (Setlec.Expr.bvar 0)
                  (Setlec.Expr.forallE
                    (Setlec.Name.anonymous)
                    (Setlec.Expr.bvar 1)
                    (Setlec.Expr.sort (Setlec.Level.zero))
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.succ (Setlec.Level.zero)) })
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))) })
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "β")
                  (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "f")
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "a")
                      (Setlec.Expr.bvar 2)
                      (Setlec.Expr.bvar 1)
                      { bi := Setlec.BinderInfo.default,
                        cod := some (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")) })
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "a")
                      (Setlec.Expr.forallE
                        (Setlec.Name.str (Setlec.Name.anonymous) "a")
                        (Setlec.Expr.bvar 3)
                        (Setlec.Expr.forallE
                          (Setlec.Name.str (Setlec.Name.anonymous) "b")
                          (Setlec.Expr.bvar 4)
                          (Setlec.Expr.forallE
                            (Setlec.Name.str (Setlec.Name.anonymous) "a")
                            (Setlec.Expr.app
                              (Setlec.Expr.app (Setlec.Expr.bvar 4) (Setlec.Expr.bvar 1))
                              (Setlec.Expr.bvar 0))
                            (Setlec.Expr.app
                              (Setlec.Expr.app
                                (Setlec.Expr.app
                                  (Setlec.Expr.const
                                    (Setlec.Name.str (Setlec.Name.anonymous) "Eq")
                                    [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")])
                                  (Setlec.Expr.bvar 4))
                                (Setlec.Expr.app (Setlec.Expr.bvar 3) (Setlec.Expr.bvar 2)))
                              (Setlec.Expr.app (Setlec.Expr.bvar 3) (Setlec.Expr.bvar 1)))
                            { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                          { bi := Setlec.BinderInfo.default,
                            cod := some (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero)) })
                        { bi := Setlec.BinderInfo.default,
                          cod := some (Setlec.Level.imax
                                   (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                   (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))) })
                      (Setlec.Expr.forallE
                        (Setlec.Name.str (Setlec.Name.anonymous) "a")
                        (Setlec.Expr.app
                          (Setlec.Expr.app
                            (Setlec.Expr.const
                              (Setlec.Name.str (Setlec.Name.anonymous) "Quot")
                              [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                            (Setlec.Expr.bvar 4))
                          (Setlec.Expr.bvar 3))
                        (Setlec.Expr.bvar 3)
                        { bi := Setlec.BinderInfo.default,
                          cod := some (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")) })
                      { bi := Setlec.BinderInfo.default,
                        cod := some (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v"))) })
                    { bi := Setlec.BinderInfo.default,
                      cod := some (Setlec.Level.imax
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.imax
                                   (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                   (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))))
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))) })
                  { bi := Setlec.BinderInfo.implicit,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                             (Setlec.Level.imax
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.imax
                                   (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                   (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))))
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v"))))) })
                { bi := Setlec.BinderInfo.implicit,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.succ (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                           (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                             (Setlec.Level.imax
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.imax
                                   (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                   (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))))
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))))) })
              { bi := Setlec.BinderInfo.implicit,
                cod := some (Setlec.Level.imax
                         (Setlec.Level.imax
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))))
                         (Setlec.Level.imax
                           (Setlec.Level.succ (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                           (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                             (Setlec.Level.imax
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.imax
                                   (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                   (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))))
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v"))))))) } }
  3
  1
  1
  0
  [{ ctor := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Quot") "mk",
     nfields := 1,
     rhs := Setlec.Expr.lam
              (Setlec.Name.str (Setlec.Name.anonymous) "α")
              (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
              (Setlec.Expr.lam
                (Setlec.Name.str (Setlec.Name.anonymous) "r")
                (Setlec.Expr.forallE
                  (Setlec.Name.anonymous)
                  (Setlec.Expr.bvar 0)
                  (Setlec.Expr.forallE
                    (Setlec.Name.anonymous)
                    (Setlec.Expr.bvar 1)
                    (Setlec.Expr.sort (Setlec.Level.zero))
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.succ (Setlec.Level.zero)) })
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))) })
                (Setlec.Expr.lam
                  (Setlec.Name.str (Setlec.Name.anonymous) "β")
                  (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                  (Setlec.Expr.lam
                    (Setlec.Name.str (Setlec.Name.anonymous) "f")
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "a")
                      (Setlec.Expr.bvar 2)
                      (Setlec.Expr.bvar 1)
                      { bi := Setlec.BinderInfo.default,
                        cod := some (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")) })
                    (Setlec.Expr.lam
                      (Setlec.Name.str (Setlec.Name.anonymous) "h")
                      (Setlec.Expr.forallE
                        (Setlec.Name.str (Setlec.Name.anonymous) "a")
                        (Setlec.Expr.bvar 3)
                        (Setlec.Expr.forallE
                          (Setlec.Name.str (Setlec.Name.anonymous) "b")
                          (Setlec.Expr.bvar 4)
                          (Setlec.Expr.forallE
                            (Setlec.Name.str (Setlec.Name.anonymous) "a")
                            (Setlec.Expr.app
                              (Setlec.Expr.app (Setlec.Expr.bvar 4) (Setlec.Expr.bvar 1))
                              (Setlec.Expr.bvar 0))
                            (Setlec.Expr.app
                              (Setlec.Expr.app
                                (Setlec.Expr.app
                                  (Setlec.Expr.const
                                    (Setlec.Name.str (Setlec.Name.anonymous) "Eq")
                                    [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")])
                                  (Setlec.Expr.bvar 4))
                                (Setlec.Expr.app (Setlec.Expr.bvar 3) (Setlec.Expr.bvar 2)))
                              (Setlec.Expr.app (Setlec.Expr.bvar 3) (Setlec.Expr.bvar 1)))
                            { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                          { bi := Setlec.BinderInfo.default,
                            cod := some (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero)) })
                        { bi := Setlec.BinderInfo.default,
                          cod := some (Setlec.Level.imax
                                   (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                   (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))) })
                      (Setlec.Expr.lam
                        (Setlec.Name.str (Setlec.Name.anonymous) "a")
                        (Setlec.Expr.bvar 4)
                        (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 0))
                        { bi := Setlec.BinderInfo.default,
                          cod := some (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")) })
                      { bi := Setlec.BinderInfo.default,
                        cod := some (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v"))) })
                    { bi := Setlec.BinderInfo.default,
                      cod := some (Setlec.Level.imax
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.imax
                                   (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                   (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))))
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))) })
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                             (Setlec.Level.imax
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.imax
                                   (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                   (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))))
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v"))))) })
                { bi := Setlec.BinderInfo.default,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.succ (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                           (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                             (Setlec.Level.imax
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.imax
                                   (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                   (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))))
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))))) })
              { bi := Setlec.BinderInfo.default,
                cod := some (Setlec.Level.imax
                         (Setlec.Level.imax
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))))
                         (Setlec.Level.imax
                           (Setlec.Level.succ (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                           (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v")))
                             (Setlec.Level.imax
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.imax
                                   (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                   (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))))
                               (Setlec.Level.imax
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                                 (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "v"))))))) } }]

/-- Annotated basis declaration (generated). -/
def quotIndA : ConstantInfo :=
  Setlec.ConstantInfo.recInfo
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Quot") "ind",
    levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "α")
              (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "r")
                (Setlec.Expr.forallE
                  (Setlec.Name.anonymous)
                  (Setlec.Expr.bvar 0)
                  (Setlec.Expr.forallE
                    (Setlec.Name.anonymous)
                    (Setlec.Expr.bvar 1)
                    (Setlec.Expr.sort (Setlec.Level.zero))
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.succ (Setlec.Level.zero)) })
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))) })
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "β")
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "a")
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.const
                          (Setlec.Name.str (Setlec.Name.anonymous) "Quot")
                          [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                        (Setlec.Expr.bvar 1))
                      (Setlec.Expr.bvar 0))
                    (Setlec.Expr.sort (Setlec.Level.zero))
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.succ (Setlec.Level.zero)) })
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "mk")
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "a")
                      (Setlec.Expr.bvar 2)
                      (Setlec.Expr.app
                        (Setlec.Expr.bvar 1)
                        (Setlec.Expr.app
                          (Setlec.Expr.app
                            (Setlec.Expr.app
                              (Setlec.Expr.const
                                (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Quot") "mk")
                                [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                              (Setlec.Expr.bvar 3))
                            (Setlec.Expr.bvar 2))
                          (Setlec.Expr.bvar 0)))
                      { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "q")
                      (Setlec.Expr.app
                        (Setlec.Expr.app
                          (Setlec.Expr.const
                            (Setlec.Name.str (Setlec.Name.anonymous) "Quot")
                            [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                          (Setlec.Expr.bvar 3))
                        (Setlec.Expr.bvar 2))
                      (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 0))
                      { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                    { bi := Setlec.BinderInfo.default,
                      cod := some (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero)) })
                  { bi := Setlec.BinderInfo.implicit,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero))
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero))) })
                { bi := Setlec.BinderInfo.implicit,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero)))
                           (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero))
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero)))) })
              { bi := Setlec.BinderInfo.implicit,
                cod := some (Setlec.Level.imax
                         (Setlec.Level.imax
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))))
                         (Setlec.Level.imax
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero)))
                           (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero))
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero))))) } }
  3
  1
  0
  0
  [{ ctor := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Quot") "mk",
     nfields := 1,
     rhs := Setlec.Expr.lam
              (Setlec.Name.str (Setlec.Name.anonymous) "α")
              (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
              (Setlec.Expr.lam
                (Setlec.Name.str (Setlec.Name.anonymous) "r")
                (Setlec.Expr.forallE
                  (Setlec.Name.anonymous)
                  (Setlec.Expr.bvar 0)
                  (Setlec.Expr.forallE
                    (Setlec.Name.anonymous)
                    (Setlec.Expr.bvar 1)
                    (Setlec.Expr.sort (Setlec.Level.zero))
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.succ (Setlec.Level.zero)) })
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))) })
                (Setlec.Expr.lam
                  (Setlec.Name.str (Setlec.Name.anonymous) "β")
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "a")
                    (Setlec.Expr.app
                      (Setlec.Expr.app
                        (Setlec.Expr.const
                          (Setlec.Name.str (Setlec.Name.anonymous) "Quot")
                          [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                        (Setlec.Expr.bvar 1))
                      (Setlec.Expr.bvar 0))
                    (Setlec.Expr.sort (Setlec.Level.zero))
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.succ (Setlec.Level.zero)) })
                  (Setlec.Expr.lam
                    (Setlec.Name.str (Setlec.Name.anonymous) "mk")
                    (Setlec.Expr.forallE
                      (Setlec.Name.str (Setlec.Name.anonymous) "a")
                      (Setlec.Expr.bvar 2)
                      (Setlec.Expr.app
                        (Setlec.Expr.bvar 1)
                        (Setlec.Expr.app
                          (Setlec.Expr.app
                            (Setlec.Expr.app
                              (Setlec.Expr.const
                                (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Quot") "mk")
                                [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                              (Setlec.Expr.bvar 3))
                            (Setlec.Expr.bvar 2))
                          (Setlec.Expr.bvar 0)))
                      { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                    (Setlec.Expr.lam
                      (Setlec.Name.str (Setlec.Name.anonymous) "a")
                      (Setlec.Expr.bvar 3)
                      (Setlec.Expr.app (Setlec.Expr.bvar 1) (Setlec.Expr.bvar 0))
                      { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                    { bi := Setlec.BinderInfo.default,
                      cod := some (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero)) })
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero))
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero))) })
                { bi := Setlec.BinderInfo.default,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero)))
                           (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero))
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero)))) })
              { bi := Setlec.BinderInfo.default,
                cod := some (Setlec.Level.imax
                         (Setlec.Level.imax
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))))
                         (Setlec.Level.imax
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero)))
                           (Setlec.Level.imax
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero))
                             (Setlec.Level.imax
                               (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                               (Setlec.Level.zero))))) } }]

/-- Annotated basis declaration (generated). -/
def quotSoundA : ConstantInfo :=
  Setlec.ConstantInfo.axiomInfo
  { name := Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Quot") "sound",
    levelParams := [Setlec.Name.str (Setlec.Name.anonymous) "u"],
    type := Setlec.Expr.forallE
              (Setlec.Name.str (Setlec.Name.anonymous) "α")
              (Setlec.Expr.sort (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")))
              (Setlec.Expr.forallE
                (Setlec.Name.str (Setlec.Name.anonymous) "r")
                (Setlec.Expr.forallE
                  (Setlec.Name.anonymous)
                  (Setlec.Expr.bvar 0)
                  (Setlec.Expr.forallE
                    (Setlec.Name.anonymous)
                    (Setlec.Expr.bvar 1)
                    (Setlec.Expr.sort (Setlec.Level.zero))
                    { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.succ (Setlec.Level.zero)) })
                  { bi := Setlec.BinderInfo.default,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))) })
                (Setlec.Expr.forallE
                  (Setlec.Name.str (Setlec.Name.anonymous) "a")
                  (Setlec.Expr.bvar 1)
                  (Setlec.Expr.forallE
                    (Setlec.Name.str (Setlec.Name.anonymous) "b")
                    (Setlec.Expr.bvar 2)
                    (Setlec.Expr.forallE
                      (Setlec.Name.anonymous)
                      (Setlec.Expr.app (Setlec.Expr.app (Setlec.Expr.bvar 2) (Setlec.Expr.bvar 1)) (Setlec.Expr.bvar 0))
                      (Setlec.Expr.app
                        (Setlec.Expr.app
                          (Setlec.Expr.app
                            (Setlec.Expr.const
                              (Setlec.Name.str (Setlec.Name.anonymous) "Eq")
                              [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                            (Setlec.Expr.app
                              (Setlec.Expr.app
                                (Setlec.Expr.const
                                  (Setlec.Name.str (Setlec.Name.anonymous) "Quot")
                                  [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                                (Setlec.Expr.bvar 4))
                              (Setlec.Expr.bvar 3)))
                          (Setlec.Expr.app
                            (Setlec.Expr.app
                              (Setlec.Expr.app
                                (Setlec.Expr.const
                                  (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Quot") "mk")
                                  [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                                (Setlec.Expr.bvar 4))
                              (Setlec.Expr.bvar 3))
                            (Setlec.Expr.bvar 2)))
                        (Setlec.Expr.app
                          (Setlec.Expr.app
                            (Setlec.Expr.app
                              (Setlec.Expr.const
                                (Setlec.Name.str (Setlec.Name.str (Setlec.Name.anonymous) "Quot") "mk")
                                [Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u")])
                              (Setlec.Expr.bvar 4))
                            (Setlec.Expr.bvar 3))
                          (Setlec.Expr.bvar 1)))
                      { bi := Setlec.BinderInfo.default, cod := some (Setlec.Level.zero) })
                    { bi := Setlec.BinderInfo.implicit,
                      cod := some (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero)) })
                  { bi := Setlec.BinderInfo.implicit,
                    cod := some (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))) })
                { bi := Setlec.BinderInfo.implicit,
                  cod := some (Setlec.Level.imax
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero)))) })
              { bi := Setlec.BinderInfo.implicit,
                cod := some (Setlec.Level.imax
                         (Setlec.Level.imax
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.succ (Setlec.Level.zero))))
                         (Setlec.Level.imax
                           (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                           (Setlec.Level.imax
                             (Setlec.Level.param (Setlec.Name.str (Setlec.Name.anonymous) "u"))
                             (Setlec.Level.imax (Setlec.Level.zero) (Setlec.Level.zero))))) } }

end Setlec
